seqan/seqan

- include/seqan/seeds/banded_chain_alignment_impl.h
- tests/seeds/test_banded_chain_alignment_interface.cpp
Fixes an issue when using std::vector for the seed chain passed to the banded-chain-aignment algorithm.
> [FIXED-#699] Fixes error with std::vector adaption in clang.

- include/seqan/consensus/consensus_builder.h
remove warning on `clang>=3.5` [-Wabsolute-value, http://llvm.org/releases/3.5.0/tools/clang/docs/ReleaseNotes.html]
> [fix] use std::abs instead of abs

- apps/fiona/tests/run_tests.py
Changes
* Changed python script to not get stuck in a deadlock due to piping the stdout and stderr.
> Fix Fiona timeout on windows.

- include/seqan/stream/zipstream/bgzfstream.h
- tests/bam_io/test_bam_file.h
Changes:
* Changes off_t to off_type the offset type used by the bgzf stream. (They are different types on Windows)
* Fixes seekoff if running queue is empty and current job does not encode the right block.
> Fixes issues with bgzf stream

- apps/snp_store/snp_store.cpp
- apps/snp_store/snp_store.h
Fixes compiler warning C4267 (convert size_t to unsigned int) on win x64.
> [FIX] Compiler warnings on windows.

- include/seqan/stream/virtual_stream.h
As a matter of fact calling the ```sgetc()``` on the ```output_stream``` on vsc++ causes the ```_IPCount``` of the ```basic_streambuf``` to be set to ```-1```. 
When calling the chunked ```write``` function, this leads to a chunk where the begin iterator is set to ```NULL``` and the end iterator to ```-1```. Hence the chunk is not recognised as empty, though it is pretty much deadly.
In the following the write method tries to put something to the begin iterator which is ```NULL``` and we get the segfault. However, specifically calling the ```sgetc()``` only for input streams leaves the  ```_IPCount``` value to ```0``` and everything works as expected. The empty buffer is reserved the first time it is called and then the buffer is instantiated and used through out the writing procedure. …
> [FIX] Razers2 test on windows.

- util/py_lib/seqan/dox/write_html.py
Hot fix to get correct escaping of html names containing numbers, e.g. ```Blosum62```
This does not solve the general problem as described here: #831, but will fix most issues with entities containing numbers in their name.
> [FIX] Fixes html name encoding.

- apps/fiona/CMakeLists.txt
Tests fail, see e.g. http://cdash.seqan.de/viewTest.php?onlyfailed&buildid=120407.
> Disabled Fiona builds on 32 bit architectures

- include/seqan/basic/alphabet_residue.h
finite alphabets may have bigger sizes than uint8 can hold.
Note that this is the type of the ValueSize and not the type of Value (which is specified manully for SimpleType).
> Fix/finitealph value size type (develop)

- include/seqan/basic/basic_stream.h
- include/seqan/sequence/adapt_std_string.h
- tests/seq_io/test_sequence_file.h
Changes are:
* Overloads the ```Chunk``` metafunction for ```std::basic_string``` to disable chunking when reading a file into this type.
* Adds forward declaration for basic append value.
* Adapts test.
> [FIXED-#866] Tokenization: Disabled chunking for std::string.

- include/seqan/stream/formatted_file.h
Enables generic open function only if ```StreamConcept``` is fulfilled.
Otherwise ```char *``` are not converted to ```const char *``` as the generic ```TStream &``` is chosen by the compiler.
> [FIXES-#904] Fixes issue #904

- include/seqan/align/evaluate_alignment.h
This adds two members to the AlignmentStats class, the absolute number of gap characters and the length of the alignment. The addition of the latter is self-explanatory, but why do we need numGaps, if numGaps always equal numGapOpens + numGapExtensions?
Well, most applications don't have information on gap openings and it would be very confusing to copmute around with them.
FWIW, I think numGapExtensions could be removed, as the opposite is true: every application that has information about the number of openings and the number of extensions, automatically has information about the total number of gap characters. However, since that would break API, I didn't remove it, yet.
since the file is @holtgrewe 's baby, I assigned it to him :)
> [FEATURE] add numGaps and alignmentLength members

- include/seqan/sequence/string_array.h
- include/seqan/sequence/string_set_base.h
- include/seqan/sequence/string_set_concat_direct.h
- include/seqan/sequence/string_set_owner.h
- tests/sequence/CMakeLists.txt
- tests/sequence/test_sequence.h
- tests/sequence/test_string_set.h
- tests/sequence/test_stringset_v2.cpp
Apparently it was not possible to append a non-concat-direct owner stringset to another one. This is a quick fix for #919, although something with tests and a more general solution would ne nicer (the trivial more general solutions do not work, I tried).
> [FIXED-#919] fix and activate StringSet tests as well as other StringSet related fixes and additions

- include/seqan/sequence/segment_prefix.h
- include/seqan/sequence/segment_suffix.h
make changes from #910 work for prefixes and suffixes, as well (not only infixes).
Will merge if there are no errors.
> [FIX] add implicit conversions similiar to infix

- include/seqan/sequence/segment_prefix.h
- include/seqan/sequence/segment_suffix.h
make changes from #910 work for prefixes and suffixes, as well (not only infixes).
Will merge if there are no errors.
> [FIX] add implicit conversions similiar to infix (develop)

- include/seqan/bam_io/write_bam.h
- include/seqan/bam_io/write_sam.h
Given the nature of the FormattedFile it would be in general possible to create a Bam/Sam file with an empty IO context. By the Sam specifications this might be valid (contains only unmapped reads), so we need a way to assert an incomplete IO context, which can happen easily as demonstrated by the following example taken from demos/tutorial/bam_io/solution1.cpp:
```cpp
BamFileIn bamIn("example.bam")
// some error checking.
BamFileOut bamOut(cout, Sam());
// Reading bamFile and writing sam file to console (as demonstrated by the demo above.) 
```
The code is valid but yields an error, since the context (contig names) of the ```bamOut``` is not set. This leads to a misleading error when writing Sam and even worse no error when writing in Bam format. The error would first appear, when one …
> [FIXED-#828] Adds assertion to writeRecord of Bam/Sam IO. 

- apps/bs_tools/tests/run_tests.py
this deactivates a test on FreeBSD that otherwise fails because of lower math precision in the FreeBSD c standard library.
Will merge later today, unless someone objects. 
@skrakau is this okay for you? it shouldnt effect anything else.
> [FIX] deactivate one test on freebsd

- include/seqan/stream/zipstream/bgzfstream.h
- tests/bam_io/test_bam_file.h
... of the next block instead of the end of the previous one, as the samtools do.
> [FIX] fixed bgzfstream tell to return the begin offset ... [master]

- apps/rabema/rabema_build_gold_standard.cpp
This fixes a build issue of rabema on VS12, likely introduced a while ago with #983.
@holtgrewe is this ok?
> [FIX] build of rabema on VS12

- include/seqan/index/index_sa_qsort.h
remove some annoying warnings
as this is a ~whitespace change I will merge it tonight.
> [FIX] remove warning that was due to incorrect parameter order

- include/seqan/basic/basic_exception.h
- util/cmake/SeqAnBuildSystem.cmake
The old behaviour was to set the macro ```SEQAN_NO_GLOBAL_EXCEPTION_HANDLER``` in order to disable it. Now we have to define the macro ```SEQAN_INSTALL_GLOBAL_EXCEPTION_HANDLER``` in order to enable it.
The build scripts are updated to set this macro for demos, tests and apps within the SeqAn library automatically. External apps and libraries have to set this macro explicitly.
> Enables global exception handler only if macro is defined 

- include/seqan/store/store_io_gff.h
- tests/store/example.gff
FragmentStore constructs a wrong AnnotationTree when parsing Gff3 files containing transcript_id fields. See #583.
> Fix FragmentStore parsing of Gff3 files

- include/seqan/gff_io/gff_io_base.h
- include/seqan/store/store_io_gff.h
- tests/gff_io/example_with_comments.gff
- tests/gff_io/test_gff_io.cpp
- tests/gff_io/test_gff_io.h
- tests/store/example.gff
- util/py_lib/seqan/dox/tpl/js/common.js
Lines start with "#" will be passed.
This fix is related with #898, #948.
> Comments lines in .gff will be skipped properly

- include/seqan/gff_io/gff_io_base.h
- tests/gff_io/example_with_comments.gff
- tests/gff_io/test_gff_io.cpp
- tests/gff_io/test_gff_io.h
Lines start with "#" will be passed.
This will close #898 .
> Comments lines in .gff will be skipped properly.

- tests/sequence/test_string_set.h
Replaces SEQAN_ASSERT_EQ calls with SEQAN_ASSERT for Strings with different alphabet type than char compatible.
> Fixes compiler warnings under VS.

- util/cmake/CMakeFindJavaCommon.cmake
- util/cmake/FindJava.cmake
This is a patch for fixing the bug (https://bugs.debian.org/772631) in cmake's findJava module. This is a temporary fix until the new cmake version, which has already the bug taken care of, becomes stable. 
This fixes issue #967.
> Fix CMake Java detection

- apps/splazers/razers_spliced.h
This fixes the splazerS test when running with the GappedXDrop extension.
The problem here is, that the function ```_extendSeedGappedXDropOneDirection ``` expects the query and data base sequence in opposite order to the seed definition.
So what comes first into the seed comes last into the extension function. :scream:
> Fixes failing splazers test.

- manual/source/StyleGuide/DoxApiDocs.rst
- util/py_lib/seqan/dox/raw_doc.py
- util/py_lib/seqan/dox/test/test_proc_doc.py
- util/py_lib/seqan/dox/test/test_raw_doc.py
Tests for the seqan.dox engine are disabled and failed in nightlies. 
This fixes the nose tests.
> Fix some issues with the nosetest of the dox engine

- include/seqan/arg_parse/arg_parse_ctd_support.h
- include/seqan/arg_parse/arg_parse_doc.h
- include/seqan/arg_parse/arg_parse_option.h
- include/seqan/arg_parse/arg_parse_parse.h
- include/seqan/arg_parse/argument_parser.h
- include/seqan/arg_parse/tool_doc.h
- tests/arg_parse/test_app.ctd
- tests/arg_parse/test_arg_parse_ctd_support.h
adds a couple of features to the arg-parser:
* abilitiy to set options as "advanced", advanced options are hidden when looking at `--help`
* add `--full-help` which shows the advanced options as well
* shortCopyright field and citation field which are shown in new LEGAL section of the default `--help`-page
* longCopyright field which enables a `--copyright` option that display the field (useful for license texts et cetera)
* SeqAn copyright information is automatically added to both fields if they are used
* fixes #536
~~Don't merge yet, as the functions for html and man-export are not yet adapted.~~
> argument parser updates

- include/seqan/align/alignment_operations.h
- include/seqan/align_extend/align_extend.h
This also fixes some things in alignExtend where it depended on broken behaviour and did unnecessary clears.
> use gaps internally for align_extend and integrateAlign

- include/seqan/find/find_multiple_bfam.h
- include/seqan/find/find_wumanber.h
- include/seqan/platform.h
Fixes build errors on VS 10 and VS 11 which did not support delete and default for move constructor and assignment function.
> Fix windows build warnings

- include/seqan/file/string_external.h
* useful when debugging memory issues
* dox and code code were inaccurate.
> [INTERNAL] make pagesize settable by macro, fix dox

- include/seqan/bam_io/bam_index_bai.h
- tests/bam_io/CMakeLists.txt
- tests/bam_io/test_bam_index.h
- tests/bam_io/test_bam_io.cpp
This Fixes #1081 
Tests added for BamIndex, _saveIndex() changed to save() and BuildIndex() changed to build()
Replaces  #1115, #1116
> BAM index file (.bai) can be saved

- include/seqan/basic/basic_exception.h
- include/seqan/basic/concept_checking.h
- include/seqan/basic/debug_test_system.h
- include/seqan/platform.h
fixes many warnings on newer gcc and clang. Note that I think it is kind of a mess that we have the same typedef for `__attribute__ ((unused))` defined so many times, but oh well.
> [FIX] many warnings on newer compilers

- manual/source/Tutorial/Iterators.rst
- manual/source/Tutorial/Sequences.rst
- manual/source/Tutorial/SequencesInDepth.rst
> Fix some typos in the manual

- util/travis/linux-cibuild.cmake
And always use 4 build/test threads.
> TravisCI: consider warnings as errors

- include/seqan/basic/iterator_adapt_std.h
previously the functions below returned Value* even if the container was const. The change directly makes dereferenciation go over the type that was defined for it instead of trying to use Value<>.
> [FIX] adapter iterator for const strings

- include/seqan/blast/blast_record.h
these are now required for Lambda, so that Lambda can work with bam io.
> [INTERNAL] for compatibility with bam io we need numerical IDs

- util/cmake/FindSeqAn.cmake
I'm using the FindSeqAn CMake module in my project. This is how it currently prioritizes its search for SeqAn:
1. Search system directories (e.g. `/usr/local/include`).
2. Search the user's specified directory (the `-D` options when calling cmake).
3. (Ignores the user's environment variables)
However, the usual behaviour of CMake modules is:
1. Search the user's specified directory (the `-D` options when calling cmake).
2. Search in directories which are defined in the user's environment.
3. Search system directories (e.g. `/usr/local/include`).
These changes fix this (perceived) bug.
> Changed includes search priorities for CMake's FindSeqAn

- include/seqan/bam_io/bam_tags_dict.h
This could be made a hotfix, but since bam_io has diverged between master and develop this would become unclean. Since it hasn't been used yet anyway, I propose to just merge into develop.
> [FIXED-#1272] change integerconcept to numericalconcept

- tests/sequence/test_string_set.h
readded test of String<short, Packed<> > on a ConcatDirect-Stringset. Test does not fail anymore because the double conversion to TString was removed.
> [FIX] Addition to StringSet: add insertValue, insert, replace #1297

- tests/sequence/test_string_set.h
[FIX] readded test of String<short, Packed<> > on a ConcatDirect-Stringset. Test does not fail anymore because the double conversion to TString was removed.
>  [Fix] Addition to StringSet: add insertValue, insert, replace #1298 

- tests/sequence/test_string_set.h
Replaces SEQAN_ASSERT_EQ with SEQAN_ASSERT to remove compiler warnings under MSVS.
> [FIX] Fixes MSVS build warnings for stringset v2 test.

- manual/source/Tutorial/PairwiseSequenceAlignment.rst
According to the definition, S stands for "soft-clipping" and X stands for "mismatch".
So "S" in the CIGAR string in ParwiseSequenceAlignment should be changed to "X".
This will fix #1309 .
> Correction of CIGAR example

- util/cmake/FindOpenMP.cmake
Followup to #1333 
Unfortunately the openmp fix was only applied to clang 3.8 so we have to force deactivate openmp for the 3.7.x series (even if built with openmp support).
> [FIX] deactivate openmp for whole clang-3.7.x series because of bug

- include/seqan/parallel/parallel_queue.h
Removed forced move of temporary object in return statement and let the compiler optimise.
> [FIX] Fixes gcc-5 warning of uninitialised value.

- include/seqan/align/global_alignment_specialized.h
Requires scoring scheme Simple for Hirschberg algorithm and asserts if affine gap costs are used.
> [FIX] Asserts wrong use of scoring scheme for Hirschberg algorithm.

- util/cmake/ctd/configure_profile_properties.cmake
This accounts for the changes made by #1296. 
Teh new ${SEQAN_DATE} is delimited by underscore instead of space. The change is made to accommodate this.
> [FIX] Replace spaces with underscores (ICC related)

- manual/source/index.rst
Replaces hardcoded link with extlink :dox:.
> [FIX] Manual: Fixes hard coded link on index page of RTD manual.

- include/seqan/bam_io/bam_tags_dict.h
- tests/bam_io/test_bam_io.cpp
- tests/bam_io/test_bam_tags_dict.h
*  Adds constructor which takes const argument.
*  Fixes incomplete dox entry.
> [FIXED-#159] Allows BamTagsDict to take const CharString as argument.

- tests/store/test_store.cpp
- tests/store/test_store_io.h
A `UcscRecord` should be able to handle records from both Genes and Isoforms UCSC files. This added test makes sure that we can load correctly both types of files into a single store.
This fixes issue #565
> A test for loading both Genes and Isoforms UCSC files in to a store

- include/seqan/basic/basic_simd_vector.h
Adds workaround for missing function ```_mm_cvtsi64_si128``` on 32 bit arch.
@esiragusa if you could have  a quick look, that would be gerat.
Fixes #903.
> [FIXED-#903] Fixes compiler warnings for simd vector.

- apps/stellar/stellar_extension.h
- include/seqan/basic/basic_simd_vector.h
- include/seqan/file/file_mapping.h
- tests/basic/CMakeLists.txt
- tests/parallel/test_parallel_atomic_primitives.h
Fixes:
* warning about integrateAlign
* diable simd_vector tests on windows platforms and fixed #warning issue
* Fixes conversion error in file_mapping.h
* Fixes test for atomic primitives.
> More compiler error/warning fixes for VS.

- util/py_lib/seqan/dox/tpl/css/common.less.css
- util/py_lib/seqan/dox/tpl/js/version.js
- util/py_lib/seqan/dox/tpl/list.html
You can add a version selector in API doc. by simply adding 
``` <script type="text/javascript" charset="utf-8" src="js/version.js"></script> ```
Check http://docs.seqan.de/seqan/master_version_test/ as an example.
To do that, I made a .php script in the documenation server.
- version.php : This will generate available versions in JSON format based on local directories.
Check http://docs.seqan.de/version.php
This will close #724.
> Add version selector in API doc.

- util/py_lib/seqan/dox/tpl/css/common.less.css
- util/py_lib/seqan/dox/tpl/js/version.js
- util/py_lib/seqan/dox/tpl/list.html
You can add a version selector in API doc. by simply adding 
<script type="text/javascript" charset="utf-8" src="js/version.js"></script>
Check http://docs.seqan.de/seqan/master_version_test/ as an example.
To do that, I made a .php script in the documenation server.
version.php : This will generate available versions in JSON format based on local directories. Check http://docs.seqan.de/version.php
> Add version selector in API doc. #1321

- demos/howto/using_zip_iterator.cpp
- include/seqan/sequence/container_view_zip.h
- tests/basic/test_basic_iterator.h
* Fixes compiler error for ```makeZipView```
* Fixes compiler error for test_basic_iteraor.
* Fixes compiler warning in demos: using_zip_iterator
> More VS fixes

- apps/razers/outputFormat.h
- apps/razers/razers.cpp
- apps/razers/razers_matepairs.h
- include/seqan/consensus/consensus_base.h
- include/seqan/index/index_dfi.h
- include/seqan/seq_io/sequence_file.h
note that for razers.cpp there were so many wild combinations of spaces and tabs that the only sensible solution was to replace all tabs with (four) spaces. Only changing the affected lines would have produced more warnings in other places...
> multiple gcc6 warnings

- apps/seqan_flexbar/general_processing.h
There is a nasty bug in the Visual Studio c++ compiler, that causes the compiler to crash when using _pragma clause wrapped by macros in a nested way. 
This happens to be a problem with our ```SEQAN_OMP_PRAGMA``` statement.
This workaround, although not beautiful, fixes this. However, seqan_flexbar is deleted in develop, so we won't support it with 2.1 anyway. So merging this into develop is not necessary.
> [FIX] flexbar: Workaround for MSVC bug.

- include/seqan/misc/bit_twiddling.h
Fixes a VS bug in bit_twiddling, see [build log](http://cdash.seqan.de/viewBuildError.php?buildid=163211):
> C:\seqan-nightly\co-git-develop\seqan-Nightly-64\include\seqan/misc/bit_twiddling.h(639): error C2146: syntax error: missing '>' before identifier 'int64_t'
-----
And removes _popCountImplGeneric, because it was only introduced for backward compatibility as stated in the following comment
>  The functions below are implemented as follows.  _popCountImplGeneric() is used if there are no intrinsics provided by the compiler (the case for Visual C++ 2008)
This [commit](https://github.com/seqan/seqan/pull/1369/files#diff-6274dcb7db964b2f07ae413d59f8bba3L339) removed the last use of the function.
> Fix VS bug: missing '>' before identifier 'int64_t'

- util/py_lib/seqan/dox/tpl/js/common.js
The nested loop was misinterpreted.
This will fix #1433 .
> display default page with null 'p' parameter properly

- util/cmake/SeqAnBuildSystem.cmake
- fixes static builds on non DEVELOP build_systems and make default, i.e. for shipping binaries
- makes static build optional for DEVELOP build system vie SEQAN_STATIC_APPS and off by default
This works, but is not very understandable. Long-term cleanup to be achieved via #1448
> static build fixes (and made optional)

- include/seqan/sequence/string_packed.h
* resize() without value is unchanged
* more efficient host-based resize() with value added
* insert() changed to where clearUnusedBits() is called before the real insert to fix the bugs we where seeing with #1074 
There is probably a larger problem hidden within ClearSpaceStringPacked_ or even the memcpy functions, but the problem only appeared with inserts and they have a workaround now, so everything is usable and regular resizes are not affected (initializing resizes should even be faster now).
PLEASE NOTE that some valgrind warnings for unintialized reads are unrelated to this and simply part of the implementation, i.e. seqan resizes() dont initialize and if only the first n bits are read and written, this implicitly read/writes the other bits although there value is irrelevant to …
> [WORKAROUND] fix insert() in packed_string

- util/cmake/SeqAnBuildSystem.cmake
zip + tar.xz instead of zip + tar.bz2
higher compression ratio and supported everywhere nowadays.
> use xz for unix packages

- include/seqan/sequence/string_set_base.h
- include/seqan/sequence/string_set_dependent_tight.h
- manual/source/Tutorial/StringSets.rst
Adds deprecation messages to the tutorial and docs.
Sovels issue #1289
> deprecate StringSet<TString, Dependent<Tight> > in docs

- apps/yara/mapper.cpp
- apps/yara/mapper.h
* Fall back to single-end mapping when paired-end library length distribution is not given nor estimable
> Yara v0.9.6

- demos/tutorial/parsing_command_line_arguments/example_with_struct.cpp
- manual/source/Tutorial/GettingStarted/ParsingCommandLineArguments.rst
- lines 45-52: Slight change of words for clarity.
- lines 131-161/183-188: Reordered a section; to not disrupt the ongoing example and state the 'Tip' at the end.
- lines 262-281: removed code block element (belongs to changes in demo file)
- all other lines: changed the type of underlining (of titles) to make everything consistent with the other pages and avoid to many different text sizes
> [CLP] Changes to Command Line Parser

- include/seqan/basic/debug_test_system.h
- include/seqan/file/file_interface.h
- include/seqan/platform.h
- include/seqan/system.h
- include/seqan/system/file_forwards.h
- include/seqan/system/file_sync.h
This PR introduces the SEQAN_ASYNC_IO macro which guards all asynchronous io code and forces use of synchronous IO if 0.
If not set manually it will set itself based on platform where the default is 0 for FreeBSD 32Bit and OpenBSD, and 1 otherwise.
> make async io optional

- demos/tutorial/indices/base.cpp
- manual/source/Tutorial/DataStructures/Indices/StringIndices.rst
This should fix build error because of missing reference in dox
> [DOC] Remove bidirectional index from docs

- apps/yara/mapper.cpp
- include/seqan/arg_parse/arg_parse_argument.h
- tests/arg_parse/test_arg_parse_ctd_support.h
- changed INPUTPREFIX to INPUT_PREFIX to be consistent with other ArgumentTypes
- added missing documentation in the dox for INPUT_PREFIX and OUTPUT_PREFIX ArgumentTypes.
@esiragusa Yara_mapper (mapper.cpp, line 116)  is affected by this could you please adjust to this change?
> [NOP, DOC] changed INPUTPREFIX to INPUT_PREFIX

- manual/source/_static/seqan_ext.css
Changes the display of the sidebar ToC:
Instead of slightly different text-font-sizes the different titles/subtitles/subsubtitles are now arranged in a bullet list with indentation.
> [FEATURE] Different display of the sidebar ToC.

- include/seqan/arg_parse/arg_parse_ctd_support.h
- util/cmake/ctd/mime.types
- Added comment to arg_parse_td_support.h
- removed redundant mime.types
- added more comprehensive list of extensions (especially to fasta, fastq, bam and sam)
> [COMMENT, DOC] Clean up mime_types and Added comment

- demos/tutorial/seeds/example1.cpp
- demos/tutorial/seeds/example1.cpp.stdout
- demos/tutorial/seeds/solution1.cpp
- manual/source/Tutorial/DataStructures/Seeds.rst
The previous "seed and extend" section was divided into "seed" and "seed and extend" sections.
This PR will separate the seed section from the ancestor more clearly.
> rework of seeds

- util/cmake/SeqAnCtdSetup.cmake
- util/cmake/ctd/configure_profile_properties.cmake
- util/cmake/ctd/plugin.properties.in
This gives flexibility to non native/external seqan apps to generate KNIME plugins that can co-exist with the seqan KNIME plugin. Right now If you generate a KNIME plugin and try to install it, that will replace the already existing SeqAn plugin, which is not nice. 
Another reason for this change is, In my opinion, not everyone is happy to name their package seqan.de.*** just because they used seqan library.
> Knime packaging - configuration options for plugin.properties

- manual/source/Infrastructure/Contribute/DoxApiDocs.rst
- manual/source/Infrastructure/Contribute/GitWorkflow.rst
- manual/source/Infrastructure/Contribute/StyleCpp.rst
- manual/source/Infrastructure/Contribute/WriteCommitMessages.rst
- manual/source/Infrastructure/Manage/WriteAppTests.rst
- manual/source/Infrastructure/Manage/WriteTutorials.rst
- manual/source/Infrastructure/Manage/WriteUnitTests.rst
- manual/source/Infrastructure/Misc/WriteNiceUnixPrograms.rst
- manual/source/Infrastructure/Use/CMakeBuildDirs.rst
- manual/source/Infrastructure/Use/FindSeqAnCMake.rst
I made a review of the Infrastructure Manual as requested by @h-2. Most of them are just :nail_care: and typos.
> Review of infrastructure - typos and grammer

- manual/source/Tutorial/Algorithms/Alignment/PairwiseSequenceAlignment.rst
- manual/source/Tutorial/DataStructures/Seeds.rst
- manual/source/Tutorial/DataStructures/Sequence/Sequences.rst
- manual/source/Tutorial/GettingStarted/AFirstExample.rst
Based on @h-2 's suggestion  from #1529 
This PR is related to #1532 
Obviously, we have to use "database" and "reference" for some cases.
For example, when we say "FragmentStore is a database",  we should not change the word "database" to "subject sequence".
That's same in "reference", "contig" and "read".
So this PR changes only a part of them, that means only changes obvious cases.
For other parts, I think we need a discussion.
> database/reference -> subject sequence

- apps/bs_tools/casbar.cpp
Corresponds to master PR #1587.
> [FIX] deletes all temp files that are generated by the app bs_tools.

- apps/yara/misc_types.h
Regression (twice) in 229a2a576b473bd4293557a18f063f59abf011c6 fixed once in 39ab4062aba6f334b9a70ca86489890c3413bafe and lost merging between master/develop.
> Yara: don't swallow base qualities

- include/seqan/align/dp_profile.h
http://docs.seqan.de/seqan/2.1.1/group_AlignmentAlgorithmTags.html is currently missing the tags for LinearGaps and AffineGaps
> [DOC] Add alignment tags of LinearGaps and AffineGaps to the docs

- README.rst
- include/seqan/align/dp_profile.h
- include/seqan/stream/formatted_file.h
- manual/source/Tutorial/DataStructures/Indices/index.rst
http://docs.seqan.de/seqan/2.1.1/group_AlignmentAlgorithmTags.html is currently missing the tags for LinearGaps and AffineGaps
> [DOC] Add alignment tags of LinearGaps and AffineGaps to the docs (develop)

- include/seqan/index/index_pizzachili.h
- include/seqan/index/index_pizzachili_string.h
- include/seqan/index/pizzachili_api.h
Referring to issue #1526.
I couldn't easily fix the Pizza&Chili-Index and thus just marked it as deprecated.
> [FIX, DOC] Mark Pizza&Chili as deprecated

- include/seqan/platform.h
Suppresses [C4503](https://msdn.microsoft.com/en-us/library/074af4b6%28v=vs.140%29.aspx) in msvc.
> [INTERNAL] Disable warning 4503 on windows

- dox/pages/index.dox
Broken links due to the recent refactoring of the manual will be changed.
(Read mapping part is removed since there is no such part in the current version.)
This will close #1705
> [DOX, FIX] change links to tutorial pages in dox

- include/seqan/platform.h
- manual/source/Infrastructure/Use/CMakeBuildDirs.rst
- manual/source/Infrastructure/Use/CustomBuildSystem.rst
- manual/source/Infrastructure/Use/FindSeqAnCMake.rst
- util/cmake/FindSeqAn.cmake
- util/cmake/SeqAnBuildSystem.cmake
- util/makefile_project/Makefile.rules
- util/makefile_project/release/Makefile
* do source-coded checks for c++14 and minimum compiler versions
* improve documentation for non-cmake consumers of SeqAn
* minor design fixes ans improvements to manual
* remove references to c++-standard from the cmake-manual
The last point depends on @marehr changing our cmake-module so that it automatically set the c++-standard to 14 if required. I am convinced this is the only right thing to do.
> use c++14 by default and complain if it isn't set

- .travis.yml
Downloads the llvm binaries and uses them instead of using apt package manager, since llvm-toolchain-precise repo is temporarily switched off.
See here for more details: http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html
> Hot fix for travis llvm builds

- apps/mason2/vcf_materialization.cpp
This fixes issue #1686. 
In mason the wrong index was being built.
> [FIX] bug in mason2 (develop)

- include/seqan/platform.h
- tests/basic/test_basic_alphabet_adapt_builtins.h
Fixes:
- test_basic_alphabet_adapt_builtins.h(221): warning #61: integer operation result is out of range
- platform.h(117): warning #1224: #warning directive: ICC versions older than 16 are not supported.
> Fix intel warnings

- include/seqan/align/global_alignment_hirschberg_impl.h
- include/seqan/align/global_alignment_myers_hirschberg_impl.h
Hopefully fixes #1711.
I could not reproduce the same error, but I found some general issues with the current code.
1. Removed all constructors and assignment operator from ```HirschbergSet_``` and let compiler generate them.
2. Resetting the vectors ```VP``` and ```VN``` was ill formed and exceeded the vector boundaries.
> [FIX] Alignment: Fixing MyersHirschberg implementation.

- include/seqan/bam_io/read_sam.h
[supersedes #1761, (sorry for trying to get pulled into your `master`)]
The official [SAM format spec](https://samtools.github.io/hts-specs/SAMv1.pdf) defines the operations {M,I,D,N,S,H,P,=,X}. Of these, '=' does not match the functor `IsAlpha`. Some tools, e.g. [ART](http://www.niehs.nih.gov/research/resources/software/biostatistics/art/) actually make use of that operation so parsing their output leads to an error like:
```
std::runtime_error: Unable to convert '150=	=	475654	-501	' into unsigned int.
```
using `NotFunctor<IsDigit>` (in place of `IsAlpha`) in `readUntil` fixes the issue.
I'll attach an example SAM file so you can reproduce the problem:
[pers_reads.min.sam.zip](https://github.com/seqan/seqan/files/334843/pers_reads.min.sam.zip)
--Cheers
> bugfix: accept '=' operations in CIGAR string

- util/cmake/SeqAnBuildSystem.cmake
#1778 ensures that the DLLs are included in the package
> [FIX] Ship ucrt, openmp and intel dlls for apps on windows

- include/seqan/platform.h
- include/seqan/sequence/container_view_zip.h
- tests/align/CMakeLists.txt
removes the failed test we see on cdash-nightlies
> [FIXES-#1779] deactivate one test on llvm35/freebsd

- include/seqan/sequence/container_view_zip.h
This should fix the regular builds on FreeBSD/clang35 again
> [FIX] make the assertion not fire wildly

- include/seqan/parallel/parallel_atomic_primitives.h
Add atomic inc and dec primitives for pointer types on windows.
> [FIX] atomic primitives for pointer types on windows.

- include/seqan/align.h
- include/seqan/align/align_interface_wrapper.h
- include/seqan/basic/basic_allocator.h
- include/seqan/basic/basic_simd_vector.h
- include/seqan/parallel/parallel_lock.h
- include/seqan/score.h
- tests/basic/test_basic_simd_vector.cpp
- tests/basic/test_basic_simd_vector.h
Disables SIMD code and fixes parallel module on ARM architecture.
Note, we still need to deactivate the tests for bs_tools for ARM, due to some rounding errors.
> Add ARM compatibility

- include/seqan/stream/stream_base.h
- include/seqan/tabix_io/tabix_index_tbi.h
Otherwise, jumpToRegion() with tabix indices fails silently, leading to
no jumping at all and weird errors.
This does not fix #1835, though.
> Extending stream_base.h to allow bgzf compression for BED files

- include/seqan/graph_algorithms.h
- include/seqan/graph_algorithms/depth_first_search.h
- include/seqan/graph_algorithms/strongly_connected_compnents.h
The previous implementation of depthFirstSearch was recursive and could crash if it got too many levels deep (10s of thousands). This new implementation is iterative and can handle larger graphs.
This PR replaces https://github.com/seqan/seqan/pull/1823, which was made against master, instead of develop.
> Nonrecursive dfs

- include/seqan/graph_msa/graph_align_tcoffee_library.h
I ran into a crash that I traced to the `getAlignmentStatistics` function in the `graph_align_tcoffee_library.h` file. This function was being called with an empty `matches` string and crashing when this line tried to dereference the iterator:
`TId id1 = sequenceId(*itFrag, 0);`
I should mention that I ran into this bug after making a number of modifications to SeqAn, so perhaps it can never happen in actual, unmodified SeqAn. But it seems like a safe change, so I thought I'll make this PR, in case you'd like to use it!
> Add check before dereferencing iterator

- include/seqan/index/index_bidirectional.h
- include/seqan/index/index_bidirectional_stree.h
- include/seqan/index/index_bifm.h
- tests/index/test_index_bifm.cpp
I kept the RevTextFibre for now in case we want to switch back to a ModifiedString.
> [FIX] BiFM: Reversed StringSet had wrong limits

- apps/bs_tools/tests/run_tests.py
This was responsible for some test failures on Debian and non-x86 architectures. See also #1861
> [FIX,TEST] only run certain tests on Linux+x86/amd64

- include/seqan/journaled_set/score_biaffine.h
- include/seqan/seeds/banded_chain_alignment_impl.h
- tests/seeds/test_align_banded_chain_impl.cpp
Checks if a score overflow is likely for a given alignment sub matrix in the banded chain alignment procedure.
Fixes #699.
> [INTERNAL, FIX-#699] Add check for possible score overflow in banded chain alignment

- apps/gustaf/msplazer.h
- apps/gustaf/msplazer_algorithms.h
- apps/gustaf/msplazer_out.h
Partial fix for https://github.com/seqan/seqan/issues/1861 
See also https://fossies.org/dox/glibc-2.24/sysdeps_2mach_2hurd_2bits_2ioctls_8h.html#aea2b0b2a11b94d258198cd2104bc79a4
> [FIX,INTERNAL] Work around GNU Hurd's TANDEM constant

- include/seqan/bam_io/bam_header_record.h
Current implementation is missing strings for parsing SO tags.
https://samtools.github.io/hts-specs/SAMv1.pdf
This will close #1839 .
> [FIX] bam_header parsing for SO tags

- include/seqan/arg_parse/arg_parse_doc.h
@smehringer can you have a look? Your changes mangled extension that contained numbers before...
> [FIX] displaying of extensions that contain numbers

- include/seqan/sequence/string_cstyle.h
`if (length(source) > 0)` in CreateArrayStringExpand_ (string_cstyle.h line 585) removed because it results in incomplete initialization of a CStyle string with an empty string.
> [FIXED-#1889] proper initialization of empty CStyle Strings (single commit)

- dox/CMakeLists.txt
This will close #1482.
If python is set to python 3.x, cmake will find 2.x and use it.
> [FIX] Find Python 2.x and use it.

- include/seqan/arg_parse/arg_parse_argument.h
- include/seqan/arg_parse/arg_parse_doc.h
- tests/arg_parse/test_arg_parse.cpp
- tests/arg_parse/test_arg_parse_argument.h
- corrected behaviour of getArgumentLabel()
- added function getArgumentType()
- added function getArgumentTypeAsString()
- Altered display of an ArgParseOption on the help page: 
... - the type of the option is displayed instead of the argumentLabel
... - instead of ```NUM NUM NUM``` the help page displays ```List of 3 NUMBER's```
> [FEATURE, INTERNAL] Altered Display of ArgParseOption in help page 

- include/seqan/index/index_fm_rank_dictionary_levels.h
(hopefully) resolves #1908 
Thanks for hinting at it, h-2!
> [FIX] Windows warning: EPR-dictionary: shift negative or too big

- include/seqan/seq_io/bam_sam.h
Fixes warning  due to PR #1920
> Fixed warning “misleadingly indented”

- CHANGELOG.rst
- demos/tutorial/blast_io/write_assignment.cpp
- include/seqan/blast/blast_record.h
- include/seqan/blast/blast_report_out.h
- include/seqan/blast/blast_tabular.h
- include/seqan/blast/blast_tabular_in.h
- include/seqan/blast/blast_tabular_out.h
This adds LCA fields to blast output and fixes some things. 
Information that was redundantly saved in each match is now accessed through the record. The previous interface is preserved for compatibility. Those parts that could be marked deprecated in the code, where. Other parts are marked deprecated through the documentation.
This is a PR I need for the next Lambda release.
> [FEATURE] add support for lca fields and fix some stuff

- include/seqan/vcf_io/read_vcf.h
Was PR #1932.
I removed contig names writing as it requires heavier changes. It would be cool if somebody implements that feature though.
Notes:
* VcfIOContext lacks contig lengths. I added code to parse that field as soon as VcfIOContext has contig lengths.
* VcfIOContext and BamIOContext would share enough functionality to have a common super context.
* Right now contig header line is stored as an unparsed header record. If we store contig names/lengths in the context and write those instead, other keys [like these](https://github.com/seqan/seqan/blob/master/tests/vcf_io/example.vcf#L5) will be lost.
> Fixed reading of contig names in VCF header

- CHANGELOG.rst
- CMakeLists.txt
- include/seqan/arg_parse/arg_parse_parse.h
- include/seqan/arg_parse/arg_parse_version_check.h
- include/seqan/arg_parse/argument_parser.h
- manual/source/Infrastructure/Use/CustomBuildSystem.rst
- manual/source/Infrastructure/Use/FindSeqAnCMake.rst
- tests/arg_parse/CMakeLists.txt
- tests/arg_parse/test_app.ctd
- tests/arg_parse/test_arg_parse_version_check.cpp
- util/cmake/SeqAnBuildSystem.cmake
Introduces 2 new macros/definition flags to select the behavior for the version update checker:
- ```SEQAN_VERSION_CHECK_OPT_IN```: enables version check but leaves it as opt-in option.
- ```SEQAN_DISABLE_VERSION_CHECK```: disables version check completely.
If non is specified the default will be enabled and fully activated.
Revises the cmake option ```SEQAN_VERSION_CHECK = disable|opt-in|opt-out```
```opt-out``` is the default.
The update version is disabled for all tests and demos but ```test_arg_parse_version_check``` which is explicitly enabled locally in the cpp.
I tested all different behaviors and adapted the tests accordingly.
@smehringer can you verify, that the test behavior matches the expected one?
> [FEATURE] Added macros for disabling, opt-in or opt-out version update check

- include/seqan/arg_parse/arg_parse_argument.h
- include/seqan/arg_parse/arg_parse_type_support.h
Uses constexpr with std::array to get rid of windows error/bug?
Seems to be a bug with brace-initilaization in static const expression?
> [FIX] Fix windows error with static const initialization with brace-initialization.

- apps/alf/CMakeLists.txt
- apps/bs_tools/CMakeLists.txt
- apps/dfi/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/fx_tools/CMakeLists.txt
- apps/gustaf/CMakeLists.txt
- apps/insegt/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/micro_razers/CMakeLists.txt
- apps/ngs_roi/CMakeLists.txt
- apps/pair_align/CMakeLists.txt
- apps/param_chooser/CMakeLists.txt
- apps/rabema/CMakeLists.txt
- apps/razers/CMakeLists.txt
- apps/razers3/CMakeLists.txt
- apps/rep_sep/CMakeLists.txt
- apps/sak/CMakeLists.txt
- apps/sam2matrix/CMakeLists.txt
- apps/samcat/CMakeLists.txt
- apps/searchjoin/CMakeLists.txt
- apps/seqan_tcoffee/CMakeLists.txt
- apps/seqcons2/CMakeLists.txt
- apps/sgip/CMakeLists.txt
- apps/snp_store/CMakeLists.txt
- apps/splazers/CMakeLists.txt
- apps/stellar/CMakeLists.txt
- apps/tree_recon/CMakeLists.txt
- apps/yara/CMakeLists.txt
- util/cmake/SeqAnBuildSystem.cmake
- Forces cmake to use CONFIG based detection instead of module based.
- Excludes stripped binaries for builds on apple.
> [HOTFIX] Fix several issues with cmake build system

- include/seqan/arg_parse/arg_parse_parse.h
- include/seqan/arg_parse/arg_parse_version_check.h
- include/seqan/arg_parse/argument_parser.h
- tests/arg_parse/test_arg_parse_version_check.cpp
- tests/arg_parse/test_arg_parse_version_check.h
- util/cmake/SeqAnBuildSystem.cmake
This includes the following changes:
- the version-check option is now a bool and can be turned off/on by specifying off/on/yes/no/1/0...
- The server is only once asked for the current versions of both app and library (result is stored in one app.version file. This might fix #1980 since it could be cause by file handling conflicts of the seqan.version file)
- The command line messages were restricted in the following way:
- app users will not be notified of new library versions, nor whether the app is not registered
- app developers (DEBUG mode) will not be notified about "new app versions" they are working on, but only on new library versions and whether they want to register their app to priovide easy version updates for their users
> [HOTFIX] Change Version Check Option to bool and manage messages via macros.

- include/seqan/align/dp_scout_simd.h
icc strikes yet again with mysteriously optimized ranged-based for loops
PS: As hot fix, since we support ICC16 on 2.3.*
> [HOTFIX] simdified alignment code

- util/cmake/FindSeqAn.cmake
in the form of a symlink
fixes #1996
> [FIX] re-add FindSeqAn.cmake as symlink

- util/cmake/FindSeqAn.cmake
Fix the fix #2007 which should have fixed #1996 
Don't use symlinks, use plain old include, which works guaranteed everywhere.
> [FIX] Fix the fix #2007 which should have fixed #1996

- include/seqan/journaled_string_tree/journaled_string_tree_impl.h
> [FIX] JST: Unused variable warning in lambda capture.

- demos/tutorial/blast_io/write_assignment.cpp
- include/seqan/blast/blast_statistics.h
- tests/blast/test_blast_output.h
In SeqAn 2.3 the blast module was adapted to use the
BlastRecord's qLength member instead of the BlastMatch's
qLength member (to remove redundancy).
But the statistics module was forgotten. This patch
adapts the statistics module, preserving the original
interface with the deprecated attribute and introducing
the new one.
=> no hard breakage, but warnings will suggest changing
to the new interface.
> [FIX,API] fix blast statistics after changes for 2.3

- apps/mason2/mason_options.cpp
- apps/mason2/mason_options.h
- apps/mason2/vcf_materialization.cpp
* VCF parsing skips unsupported variants instead of segfaulting
* Allowed compressed file extensions
> Small fixes to Mason

- include/seqan/index/index_fm_rank_dictionary_levels.h
Note that ```Size<TConfig>``` was default type size...
> FMIndex: removed wrong Size spec for RankDictionary

- include/seqan/score.h
- include/seqan/simd.h
- util/cmake/SeqAnBuildSystem.cmake
- util/cmake/SeqAnSimdUtility.cmake
Changes:
* Disable 32bit simd builds (one half of the errors)
* Hide performance warnings when testing or when NDEBUG is defined
* Disable clang3.7 avx2 seqan-simd builds. It generates wrong shuffle code.
* Disable clang4.0 avx512_skx and avx512_cnl seqan-simd builds. The compiler crashes.
* Fix not working -DSEQAN_ARCH_SSE4=1
* Massive errors on darwin (on this machine SEQAN_ARCH_SSE4 was defined and showed a missing simd.h include)
Still open:
* Icpc-17 errors in the alignment code
> Fixes simd related errors on dash-board

- manual/source/Tutorial/GettingStarted/ParsingCommandLineArguments.rst
Change modifyText() to modifyString() to be consistent with the examples in the Parsing Command Line Arguments tutorial
> Change modifyText() to modifyString()

- include/seqan/journaled_string_tree/journaled_string_tree_traverser.h
- tests/journaled_string_tree/test_journaled_string_tree_traverser.cpp
- tests/journaled_string_tree/test_journaled_string_tree_traverser.h
Extends the interface of the jst traverser to check whether the traverser is at the base or in some branch.
> [FEATURE] add isBase function for traverser.

- apps/micro_razers/micro_razers.cpp
- apps/sgip/sgip.cpp
- apps/splazers/splazers.cpp
Will lead to better unix 'man' manual pages
> [DOC] Normalize some command line help

- include/seqan/stream/iostream_bgzf.h
- manual/source/Infrastructure/Use/CustomBuildSystem.rst
See #1899 for my remarks on the potential trouble with spawning a hardcoded number of threads.
My understanding is that it is unlikely that a consistent mechanism for developers to control how many threads seqan will use for what will be implemented in 2.x.
This patch provides at least compile time control to devs writing applications against seqan for BAM I/O.
> Add BGZF_NUM_THREADS

- CMakeLists.txt
If dox are not built, it makes no sense to attempt a manual build.
This test is not covered by unit tests so you can ignore the test results, but instead please review extra carefully!
> [FIX] deactivate manual, if dox is deactivated, because of dependency

- dox/CMakeLists.txt
- util/cmake/SeqAnBuildSystem.cmake
- util/py_lib/CMakeLists.txt
One cmake python call to rule them all
#1482 (issue that had python as symlink to python3)
#1916 (@xenigmax fixed this for dox)
#1969 (@xenigmax another fix for dox?)
#2003 (@xenigmax another fix #1992 for dox)
> [FIX] Force python2.7 in SeqAnBuildSystem

- include/seqan/simd.h
- util/cmake/SeqAnSimdUtility.cmake
Fixes #2017 and current >1000 build-errors on cdash fo gcc 4.9.
Errors:
> /.../Linux-3.16.0-4-amd64_g++-4.9_64/tests/simd/test_simd_vector.h:122:7: error: 'constexpr SimdVectorTestCommon<__vector(32) signed char>::SimdVectorTestCommon()' conflicts with a previous declaration
>
> class SimdVectorTestCommon : public seqan::Test
>       ^
> Disable simd for gcc4.9

- include/seqan/gff_io/gff_io_base.h
This fixes issue #2112.
The fix also includes  possibility to ignore empty lines and right before directives/comments
> [FIX] fixes GFF reading in the case of '###' terminated files

- util/cmake/SeqAnSimdUtility.cmake
* SEQAN_SIMD might not be detected, because of some left over platform flags (e.g. `-mavx2`, `-mavx512f`) from a previous run.
* Force compiler to use avx512 instructions in try-compile
> Fix small issue in SeqAnSimdUtility

- include/seqan/arg_parse/tool_doc.h
When multiple arguments are present, the tool doc displays the arguments `1..n` indented by `10` spaces, if no description to the list item is present.
> [FIX] Fixes alignment of arguments in text-tool-doc if no argument description is present.

- include/seqan/arg_parse/arg_parse_argument.h
- tests/arg_parse/test_arg_parse.cpp
- tests/arg_parse/test_arg_parse_argument.h
Fixes #1988 
@h-2 Can you maybe try this on real use cases before merging? It seams to work fine but just to be sure since I think no app (in the seqan repo) uses this functionality.
> [ENHANCEMENT,TEST] directory argument/option now also accept trailing whitespaces

- include/seqan/index/index_fm_lf_table.h
- include/seqan/index/index_fm_rank_dictionary_wt.h
Saves some time when calling ``getOccurrences()``.
Before, the value (i.e. character) in the bwt at a given position was retrieved by going down the tree and then the rank was computed up to the given position using that value (which leads to going down the tree twice). Now the tree is only processed once and the value/character is retrieved while computing the rank.
> [FIX] Don't go down the wavelet tree twice when retrieving hits

- CHANGELOG.rst
- include/seqan/bam_io/bam_index_bai.h
Fixes #2213 
Some explanation, because this bug seems to exist for quite a while:
Goal: Jump to the beginning of a region `[regionStart, regionEnd]`
In the current master branch (seqan 2.3) the `jumpToRegion()` jumps to highest candidate offset (candidate offset of bam index blocks) whose position is still smaller than `regionStart`. Reaching this index block, it sets the bam file stream to the first record it finds. This is most of the time not even near the actual `regionStart` and the information of `hasAlignments` was also wrong, since it has no knowledge about the actual region `[regionStart, regionEnd]`.
In the current develop branch, were the issue in master was reported by #1944, the `hasAlignment` parameter was partially fixed by PR #2098 to only be set to true: IF the very first …
> [FIX] Fixes BAM jumpToRegion functionality.

- include/seqan/simd/simd_base.h
- include/seqan/simd/simd_base_seqan_interface.h
- include/seqan/simd/simd_base_umesimd_impl.h
- util/cmake/SeqAnSimdUtility.cmake
- detects internal compiler error of gcc5 raised in comparison operator of 64 byte vector.
- fixes type truncation when using createVector with different vector host type and value type.
> Fixes some SIMD compile issues using gcc5

- include/seqan/simd/simd_base.h
- include/seqan/simd/simd_base_seqan_interface.h
- include/seqan/simd/simd_base_umesimd_impl.h
This reverts commit 6df610cdf93d82efd631790d3dc799ab956d17f7.
It broke UME Simd and I could not reproduce the error after reverting it.
> Revert "[FIX] SIMD: Fixes createVector truncated value type issue."

- include/seqan/arg_parse/tool_doc.h
> [INTERNAL] Fixes man page output: Escape special characters '.' or ''' at the beginning of a line.

- apps/yara/CMakeLists.txt
- apps/yara/mapper.cpp
- apps/yara/mapper.h
- apps/yara/misc_options.h
We have a use case for this where we map against multiple alternative references which are clustered beforehand, allowing a fixed number of errors N during clustering. To guarantee that we do not miss hits against then hidden members of the reference clusters, we need to map best + N errors.
@esiragusa What do you think about merging this?
> Yara: Add option to specify strata by absolute errors

- include/seqan/align/dp_cell.h
- tests/align/test_align.cpp
- tests/align/test_alignment_algorithms_global.h
- tests/align/test_alignment_dp_cell.h
Fix for #2331: The problem was a wrong alignment result and a wrong score, whenever TScoreValue is a float type in dp alignment computation. 
The issue was caused by the border initialization, which was aimed to be -inf/2 and implemented as std::numeric_limits::min / 2. This works fine for integer types, but for floating point types `std::numeric_limits::min` gives the closest positive value to 0. When adding gap extension cost to ≈0 in the first column and row, this leads in general to a better score in the max-function than the intended gap open cost, so all matrix values become wrong. 
I changed the implementation to `std::numeric_limits::lowest`, which does not change anything for integer types, but for floating point types it represents the smallest possible value as intended.
> [FIX-#2331] correct infinity value in dp alignment

- manual/source/Infrastructure/Contribute/GitWorkflow.rst
- manual/source/Infrastructure/Manage/Releases.rst
- manual/source/Tutorial/Algorithms/Alignment/MultipleSequenceAlignment.rst
- manual/source/Tutorial/DataStructures/Store/FragmentStore.rst
- manual/source/Tutorial/DataStructures/Store/GenomeAnnotations.rst
The only semantic change is the order of the gap open and gap extension penalty parameters in MultipleSequenceAlignment.rst, which I checked against code examples from other tutorials (it was suspicious that extension would cost more than opening).  The rest are minor typo fixes.
> Fix order of gap open and gap extend parameters, and some typos, in tutorials

- include/seqan/seeds/seeds_global_chaining.h
- tests/seeds/test_seeds_global_chaining.cpp
This fixes #2318 
The if-clause was ill-formed and not consistent with the original Gusfield algorithm. The minimal example that caused the assert in the referenced issue was included as a test case.
> [FIX] Fixes bug in chainSeedsGlobally().

- include/seqan/bed_io/read_bed.h
- tests/bed_io/test_bed_io.cpp
This PR adds compatibility for BED12 files:
- allow additional comma at the end of _blockSizes_ and _blockStart_
- allow RGB field to contain a single `0`, which is interpreted as 0,0,0
- fix newline problems: Two lines were skipped, if there was no additional text after the 12th column.
> [FIX-#2346] correct BED12 file parsing, compatible with UCSC

- include/seqan/basic/debug_test_system.h
The underlying function of a test case is templatized and thus needs an explicit call `test_name<true>` to invoke.
This only happens when `SEQAN_ENABLE_TESTING` is not set.
> directly building test cases with g++ fails

- apps/alf/CMakeLists.txt
- apps/bs_tools/CMakeLists.txt
- apps/dfi/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/fx_tools/CMakeLists.txt
- apps/insegt/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/rabema/CMakeLists.txt
- apps/razers3/CMakeLists.txt
- apps/sak/CMakeLists.txt
- apps/sam2matrix/CMakeLists.txt
- apps/samcat/CMakeLists.txt
- apps/seqan_tcoffee/CMakeLists.txt
- apps/snp_store/CMakeLists.txt
- apps/stellar/CMakeLists.txt
- apps/tree_recon/CMakeLists.txt
- apps/yara/CMakeLists.txt
- util/cmake/SeqAnBuildSystem.cmake
Adds automatic testing for the CTD exporter of the SeqAn apps, in order to detect downstream errors as by #2280 earlier in the pipeline.
Especially, if the CTD schema is updated.
This will break the builds but #2285 will fix it.
So after merging this, #2285  can be rebased and should fix all errors.
> Infrastructure adds automatic testing of correct ctd export of our tools

- include/seqan/graph_types/graph_iterator_edge.h
- include/seqan/graph_types/graph_iterator_outedge.h
- tests/graph_types/test_graph_types_iterators.cpp
Solves a problem (#2360) with Graph Iterators, when initialized with an empty graph. 
The constructor checks, whether the vertex string is not empty before accessing the first vertex. Furthermore, the iterator of an empty graph must be always in the condition _atEnd_. 
fixes #2360
> [FIX-#2360] Initialization of iterators over empty graphs

- apps/yara/CMakeLists.txt
- apps/yara/mapper.cpp
With the latest version of yara, the  mapper cannot be executed within KNIME anymore.
The reason is a subtle difference in the usage of default values between the argument parser and the GKN. 
The GKN sets the default values stored in the CTD as input parameters for the tool execution. But the argument parser differentiates whether an option was set or defaulted. So while it works for the command line in KNIME the check whether both options strata-count and strata-rate were set causes an abort, even though they were intialized with their default values.
Despite this issue, I think there is a general flaw in the usage of the default values here.
Both strata-rate and strata-count are initialized with default values, 0 in particular. But for the strata-count the default value is never read, …
> [FIX] Fixes option condition so that yara works in KNIME again.

- include/seqan/graph_msa/graph_align_tcoffee_msa.h
- tests/graph_align/test_graph_match_refinement.h
Fixes a bug in SeqAn::T-Coffee that recalculates and overwrites the scores of all matches provided in a library file. From now on, the scores of the library file will be added straight to the match graph.
> [FIX] avoid ReScore for matches in T-Coffee lib files

- include/seqan/align/global_alignment_banded.h
- include/seqan/align/global_alignment_unbanded.h
- include/seqan/align/local_alignment_banded.h
- include/seqan/align/local_alignment_unbanded.h
- include/seqan/align_parallel/parallel_align_interface.h
Currently there are no wrapper interfaces for the accelerated alignment with trace. This fixes it now.
> [FIX] Add missing wrapper interfaces for accelerated alignment with trace

- apps/rep_sep/rgraph_base.h
- include/seqan/align/align_base.h
- include/seqan/align/gaps_iterator_anchor.h
- include/seqan/align/gaps_iterator_array.h
- include/seqan/basic/iterator_counting.h
- include/seqan/basic/iterator_position.h
- include/seqan/basic/triple_packed.h
- include/seqan/find/find_myers_ukkonen.h
- include/seqan/index/index_esa_base.h
- include/seqan/index/index_fm_stree.h
- include/seqan/index/index_qgram.h
- include/seqan/index/index_qgram_openaddressing.h
- include/seqan/index/index_sa_stree.h
- include/seqan/index/shape_gapped.h
- include/seqan/index/shape_onegapped.h
- include/seqan/misc/interval_tree.h
- include/seqan/modifier/cyclic_shape.h
- include/seqan/sequence/iter_concat_virtual.h
- include/seqan/sequence/segment_infix.h
- include/seqan/sequence/segment_prefix.h
- include/seqan/sequence/segment_suffix.h
- include/seqan/sequence/string_packed.h
- include/seqan/store/store_annotation.h
- tests/modifier/helpers.h
- tests/sequence/test_sequence.h
GCC9 introduces new rules when implicitly defaulted copy constructor and copy assignment are valid.
If there is a user-provided copy constructor, the copy assignment has to be provided too, and vice versa.
Additionally, a user-provided destructor requires both copy constructor and assignment to be defined.
Violating this rule results in a `deprecated-copy` warning (e.g. when using `SeqFileIn`):
```
seqan/include/seqan/stream/guess_format.h:159:14: warning: implicitly-declared [COPYCTOR] is deprecated [-Wdeprecated-copy]
159 |     TLowcase lowcaseFileName(fileName);
seqan/include/seqan/sequence/segment_prefix.h:117:5: note: because 'seqan::Segment<const char*, seqan::PrefixSegment>' has user-provided [COPYASSIGNMENT]
117 |     operator = (Segment const & source)
```
Where COPYCTOR and …
> [FIX] warnings on gcc9

- include/seqan/blast/blast_report_out.h
- include/seqan/blast/blast_tabular_out.h
Two of the template arguments of BlastMatch were not properly forwarded.
Anyone that has a minute to review would be appreciated. I really need this for lambda so if all tests pass but there are no reviews within the next days (which is totally OK), I will merge since it is really just minor and I consider the blast module my turf :laughing:
> [FIX] some template args were missing

- include/seqan/align/evaluate_alignment.h
- include/seqan/blast/blast_io_context.h
Two fixes:
* the first uses explicit convert instead of static_cast. Relevant because SeqAn2 concepts only require that convert is available and not that a gapped alphabet is actually cast-able to it's non-gapped version. When combining with SeqAn3 gapped alphabets, this breaks.
* Two unused buffers prevented comparability in certain situations.
> Small fixes for Lambda

- include/seqan/blast/blast_report_out.h
In Blast I/O the record and the match have a `.qLength` member. The one on the match has been deprecated, but internal code still (incorrectly) used it instead of the record's member.
This PR fixes this behaviour by using the record's member if it is != 0 (has been set to something by the user).
> [FIX] don't rely on deprecated match.qLength

- include/seqan/seq_io/fasta_fastq.h
Passing FASTA files with `*.fas` extensions to the argument parser fails currently.
> [FIX] Added *.fas file extension to FASTA files

- include/seqan/align/dp_formula.h
- include/seqan/align/dp_formula_affine.h
- include/seqan/align/dp_formula_dynamic.h
- include/seqan/align/dp_formula_linear.h
- tests/align/CMakeLists.txt
- tests/align/test_align_bugs.cpp
- tests/align/test_alignment_dp_formula.h
In local alignment the comparison against 0 was fixed when
computing all traces. The rational behind this is that
whenever the score at a cell is not greater than 0 the trace
must be set to NONE to indicate the begin of the
alignment. Otherwise, a scoring matrix that evaluates to
score 0 for two residues might falsely add the substitution
to the alignment.
fixes #2417
> [FIX] Fixes #2417: Difference between SIMD and serial local alignment

- include/seqan/basic/allocator_interface.h
All recent macos versions should support posix_memalign but somehow the currently used macros are not sufficient anymore.
> [FIX] Aligned allocation for newer macos platforms.

- .travis.yml
- include/seqan/index/index_pizzachili.h
- include/seqan/sequence/sequence_interface.h
- manual/requirements.txt
- util/travis/linux-cibuild.sh
(1) We need some specialised overloads for `String`, `StringSet` and `Segment`, because the general overload for `begin` will be ambiguous in the context `std::ranges::begin` is evaluated in (https://eel.is/c++draft/range.access.begin#2.5).
(2) Including `index.h` will cause a deprecation warning even though the PizzaChili Index is not used; I removed the deprecation warning, because there is still one in the `impl::` function that is called when the index is actually created.
> Fixes for cpp20

- apps/seqan_tcoffee/seqan_tcoffee.cpp
This PR fixes an error, where the argument parser of T-Coffee requires the file ending `.mums`, while in the implementation the ending `.mummer` was considered. 
Solution: The implementation checks for files ending with `.mums`.
> [FIX] T-Coffee file ending for MUM segments

- include/seqan/find/find_horspool.h
If `it` is already at the end, we might dereference nonsense and lookup nonsense in `data_map`.
> [FIX] out of bounds access

- manual/source/bibtex.json
- manual/source/conf.py
sphinxcontrib.bibtex was updated from 1.0.0 to 2.0.0
Usage changed a little bit:
* bib file must be configured
* it creates a json file, if this file does not exist, a warning (=error) is emitted, and sphinx must be rerun. It is recommded to put it into the repository if sphinx should only be run once.
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html
> [FIX] newest sphinxcontrib.bibtex does not work

- .github/workflows/ci.yml
- .github/workflows/ci_win.yml
- include/seqan/arg_parse/arg_parse_version_check.h
Commit 1: Rerun failed tests. This probably circumvents the spurious fails until we find a permanent solution
Commit 2: Add a timeout to the version check. The tests do not fail if the server is down, but the version check does not time out if the server is down.
> [INFRA] make CI more robust

- include/seqan/find/find_horspool.h
This seems to fix https://github.com/seqan/product_backlog/issues/261#issuecomment-746779628
In the test, we search (internally) for `GTGGT` in `GTG`. On windows, this sometimes returns `true`.
> [FIX] wrong results when searching with horspool

- util/cmake/seqan-config-version.cmake
- util/cmake/seqan-config.cmake
This PR allows `find_package(SeqAn 2.4)`.
TODO: if we package seqan, include `seqan-config-version.cmake`
> Rework seqan config.cmake

- .github/workflows/ci.yml
- .github/workflows/ci_win.yml
macOS runs sometimes use longer than 2 hours (~95% complete at that time).
> [INFRA] increase CI timeout to 180 minutes

- include/seqan/modifier/modifier_reverse.h
- include/seqan/modifier/modifier_shortcuts.h
- tests/modifier/test_modifier.cpp
- tests/modifier/test_modifier_shortcuts.h
If a ConcatDirect StringSet with packed strings is reversed (and OpenMP supported), reversing the strings is currently undefined behavior.
This is critical, because reversing the strings will use the parallel implementation by default.
These types of string sets are often used for string indices with a low memory footprint.
> [FIX] UB reverse on packed strings

- include/seqan/stream/stream_base.h
MagicHeader<TFormat>::VALUE is != NULL for all specialisations, expect Nothing
> [FIX] -Waddress

- include/seqan/index/find2_index_approx.h
In the case a search scheme with only one part is being used
(s.pi.size() == 1) an invalid read is being produced.
Every part has to be read in forwards or backwards direction. This
depends on the previous parts. Normally the shown code is only being
executed with the second or above part, this might be different in the
case when only one part exists. In general it doesn't matter if the
first part is being read in forward or backwards direction.
The suggested code change is derived from the equivalent seqan3 code
base with a similar adjustment
https://github.com/seqan/seqan3/blob/58429c14117444dba6448713b0ad9c3160af0ed3/include/seqan3/search/detail/search_scheme_algorithm.hpp#L429
> [FIX] FMIndex/approximate using short search schemes

- include/seqan/bam_io/bam_alignment_record.h
- include/seqan/bed_io/bed_record.h
- include/seqan/rna_io/rna_record.h
- include/seqan/roi_io/roi_record.h
- include/seqan/vcf_io/vcf_record.h
The definition of some variables are missing. This PR adds them.
> [FIX] add missing definition of static variables

- util/cmake/seqan-config.cmake
```
[cmake]   CMake Warning (dev) at util/cmake/seqan-config.cmake:209 (EXEC_PROGRAM):
[cmake]   Policy CMP0153 is not set: The exec_program command should not be called.
[cmake]   Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
[cmake]   command to set the policy and suppress this warning.
[cmake] 
[cmake]   Use execute_process() instead.
```
> [FIX] CMake: Use execute_process

- CHANGELOG.rst
The Changelog is probably quite incomplete, but at least the supported/tested compilers are now correct.
> [DOC] Update changelog

- .github/workflows/ci_win.yml
- apps/mason2/README
- apps/mason2/genomic_variants.cpp
- include/seqan/graph_types/graph_impl_hmm.h
- util/bin/demo_checker.py
This fixes #2511 
Let's see what the tests say as it seems to be an rather invasive fix.
So the reported error in Debug mode, was that a SNP is within the region of a deletion.
```
Assertion failed : snpRecord.getPos() != svRecord.getPos() should be true but was 0 (Should be generated non-overlapping (snp pos = 148753369, sv pos = 148753369).)
```
What happens is the following: 
1) mason_variator simulates SVs
2) mason_variator simulates SNP/Indels: It goes over every position in the contig (e.g. a chromosome) and at the same time maintains the current SV of the region to avoid overlaps. It jumps to the next SV if the current position is greater than the end position of the current SV [`pos >= svRecord.endPosition()`](https://github.com/seqan/seqan/blob/main/apps/mason2/mason_variator.cpp# …
> [FIX] mason_variator: Fix StructuralVariantRecord::endPosition() for deletions.

- include/seqan/bam_io/write_bam.h
The BAM output is missing the `@SQ` headers derived from the context.
According to the SAM spec, the header *should* contain the references.
When rewriting a seqan2 BAM with `samtools view -hb`, the `@SQ` lines are silently regenerated (from the `l_name`, `name`, and `l_ref` data fields in the list of reference information in the BAM file).
> [FIX] Missing SQ header in BAM output

- include/seqan/align/dp_matrix_navigator_score_matrix.h
Resolves #2524 
We are in this case: https://github.com/seqan/seqan/blob/main/include/seqan/align/dp_algorithm_impl.h#L691
Some time later, this line will also be called on the first Column:
https://github.com/seqan/seqan/blob/45fa675f63514f1b95f746644bf5648379d0101e/include/seqan/align/dp_algorithm_impl.h#L361
However, there is no previous column.
<details><summary>Testcode (click to expand)</summary>
```cpp
#include <iostream>
#include <seqan/align.h>
int main()
{
seqan2::String<char> const seq1{"CDFGHC"};
seqan2::String<char> const seq2{"CDEFGAHC"};
seqan2::Align<seqan2::String<char>, seqan2::ArrayGaps> align{};
seqan2::resize(seqan2::rows(align), 2);
seqan2::assignSource(seqan2::row(align, 0), seq1);
seqan2::assignSource(seqan2::row(align, 1), seq2);
int const score = …
```
> [FIX] Segfault in GlobalAlignment

- include/seqan/align_parallel/wavefront_alignment_task.h
- include/seqan/align_parallel/wavefront_task.h
- include/seqan/align_parallel/wavefront_task_executor.h
- include/seqan/align_parallel/wavefront_task_queue.h
In the original line `appendValue(taskQueue, *taskGraph[0][0])`, the std::shared_ptr was dereferenced and appended to the taskQueue. This taskQueue was then used by the executor. On rare occassions (depending on which thread does what and when), it could happen that the executor tries to access the task* after it was destructed when all std::shared_ptr instances were destructed.
By passing the task via shared_ptr instead of raw pointer, we can ensure that any access by the executor is valid.
> [FIX] heap-use-after-free

- include/seqan/align/dp_matrix_navigator_score_matrix.h
Instead is_same_v<...>. Latter is C++17 and the only thing that fails when compiling with C++14
> [MISC] Use is_same<...>::value

- include/seqan/seeds/banded_chain_alignment.h
- include/seqan/seeds/banded_chain_alignment_traceback.h
- tests/seeds/CMakeLists.txt
- tests/seeds/test_align_banded_chain_issue_2540.cpp
Not fixing #2540 but working around assert that could in release mode lead to UB. This way there is a decent abortion when two traces cannot be merged.
Looking deeper into the code suggests that a larger rework is necessary and better be dealt with when implementing such algorithm inside of modern SeqAn versions.
> Converts assertion to exception in case two traces cannot be merged.

- apps/alf/CMakeLists.txt
- apps/bs_tools/CMakeLists.txt
- apps/dfi/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/fx_tools/CMakeLists.txt
- apps/gustaf/CMakeLists.txt
- apps/insegt/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/micro_razers/CMakeLists.txt
- apps/ngs_roi/CMakeLists.txt
- apps/pair_align/CMakeLists.txt
- apps/param_chooser/CMakeLists.txt
- apps/rabema/CMakeLists.txt
- apps/razers/CMakeLists.txt
- apps/razers3/CMakeLists.txt
- apps/rep_sep/CMakeLists.txt
- apps/sak/CMakeLists.txt
- apps/sam2matrix/CMakeLists.txt
- apps/samcat/CMakeLists.txt
- apps/searchjoin/CMakeLists.txt
- apps/seqan_tcoffee/CMakeLists.txt
- apps/seqcons2/CMakeLists.txt
- apps/sgip/CMakeLists.txt
- apps/snp_store/CMakeLists.txt
- apps/splazers/CMakeLists.txt
- apps/stellar/CMakeLists.txt
- apps/tree_recon/CMakeLists.txt
- apps/yara/CMakeLists.txt
- util/bump_app_versions.sh
Some app versions are out of sync. E.g., there is already a yara 1.0.3 on packages.seqan.de, but the version wasn't bumped afterwards.
To avoid clashes, just bump all the app versions.
> [INFRA] Bump app versions

- apps/mason2/mason_simulator.cpp
- include/seqan/stream/iostream_bgzf.h
- include/seqan/stream/iostream_bzip2_impl.h
- include/seqan/stream/iostream_zip_impl.h
- include/seqan/stream/iter_stream.h
> [FIX] mason2: Detect when out of disk space.

- include/seqan/basic/pair_bit_compressed.h
Note that, at time of writing, godbolt's MSVC is 19.43. Current and the runner's version is 19.44.
Simplest test is `test_basic_aggregate`.
Using `unsigned` instead of `int` in `template <typename T1, typename T2, template <unsigned, unsigned> typename TSpec, int BITSIZE1, int BITSIZE2>` causes another ICE for razers, param_chooser, splazers, and others.
> [FIX] ICE on MSVC 19.44
