seqan/seqan

- apps/gustaf/gustaf_matepairs.h
- apps/gustaf/join_mates.cpp
- apps/gustaf/msplazer_out.h
- apps/gustaf/stellar_routines.h
Fixed slow import of sequences.
> Feature/gustaf 1.0.1

- util/py_lib/seqan/dox/tpl/sections.html
Disabled lexicographical sorting of enum values.
> [FIXES-#780] Disable sorting of enum values.

- tests/pipe/test_pipe.cpp
> [fix] test_pipe to catch up with amino acid change

- util/travis/linux-cibuild.cmake
> Improve CI builds

- include/seqan/consensus/overlap_info_computation.h
see http://cdash.seqan.de/viewBuildError.php?type=1&buildid=118021
[sorry for pushing this into upstream repo, will remove it after merge]
> [fix] warnings in seqcons2 on 32bit

- apps/gustaf/create_stellarmatches_from_file.h
- apps/gustaf/gustaf_matepairs.h
- apps/gustaf/msplazer.h
- apps/gustaf/msplazer_main.h
- apps/gustaf/msplazer_out.h
- apps/gustaf/msplazer_parse_options.h
- apps/gustaf/stellar_routines.h
- apps/gustaf/tests/pairedEnd_st1_l30.gff
Added simple paralization of Stellar input and added otion parameter to define number of threads. Cleaned up some more unnecessary ID comparisons.
> Feature/gustaf 1.1.0

- demos/align/compute_alignment_stats.cpp
- demos/align/compute_alignment_stats.cpp.stdout
- include/seqan/align/evaluate_alignment.h
Merges adaptions to alignment statistics into develop.
> [FEATURE] Merges changes from #784 into develop.

- apps/yara/CMakeLists.txt
- apps/yara/misc_options.h
- util/cmake/SeqAnBuildSystem.cmake
Please use SEQAN_APP_VERSION in all the apps.
> Yara: use SEQAN_APP_VERSION

- include/seqan/file/string_external.h
- include/seqan/stream/file_stream.h
... as it clashed in /usr/include/mach/i386/vm_param.h on Mac
Can we please merge this into the 2.0 release
> [FIX] renamed PAGE_SIZE -> PAGESIZE

- include/seqan/sequence_journaled/journal_entries_sorted_array.h
> [INTERNAL] JournaledSequence: splits public interface to make more efficient internal interface with iterators accessible.

- apps/razers3/README
@weese please remember to follow the gitflow - your commit went only to master!
> Hotfix: RazerS README

- include/seqan/index/shape_minimizer.h
> Fixed name clash of ReverseComplement_

- include/seqan/basic/basic_stream.h
- include/seqan/sequence/adapt_std_string.h
- tests/seq_io/test_sequence_file.h
To be merged into develop (see #870).
> [FIXED-#866] Tokenization: Disabled chunking for std::string.

- include/seqan/seq_io/fai_index.h
> Optimized fasta index construction

- include/seqan/stream/tokenization.h
this makes readUntil work on const sequences as well.
> [fix] remove const from type (develop)

- include/seqan/stream/tokenization.h
this makes readUntil work on const sequences as well.
> [fix] remove const from type (master)

- manual/source/Tutorial/GettingStarted.rst
* Hotfix #901 had been closed rather than merged.
* Hotfix #882 had different commits than #881.
> Synced develop with master

- include/seqan/index/find_index_lambda.h
- include/seqan/index/index_base.h
- include/seqan/index/index_esa_stree.h
- include/seqan/index/index_fm.h
- include/seqan/index/index_qgram.h
- include/seqan/index/index_sa_stree.h
Public interface for various internal implementations of single/multiple backtracking, each one being bad in some aspect. The possibility of Iterating trees as tries would greatly simplify things...
> Improved the lambda-based Index find()

- demos/tutorial/bam_io/example1.cpp
- manual/source/Tutorial/IndexedFastaIO.rst
- manual/source/Tutorial/StringSets.rst
I need this to be merge before noon. This will also fix #908
> [DOC] typos and corrected code fragment

- demos/tutorial/bam_io/example1.cpp
- include/seqan/align/gaps_anchor.h
- include/seqan/bam_io/cigar.h
- include/seqan/basic/basic_stream.h
- include/seqan/index/index_qgram_openaddressing.h
- include/seqan/sequence/segment_infix.h
- include/seqan/sequence/string_set_base.h
- include/seqan/stream/formatted_file.h
- manual/source/Tutorial/IndexedFastaIO.rst
- manual/source/Tutorial/StringSets.rst
> Added open() and save() for OpenAddressing QGramIndex

- apps/yara/bits_context.h
- apps/yara/mapper.cpp
- apps/yara/tests/gold/adeno-reads_1.t1.sam
- demos/tutorial/bam_io/example1.cpp
- include/seqan/align/gaps_anchor.h
- include/seqan/arg_parse/arg_parse_argument.h
- include/seqan/bam_io/cigar.h
- include/seqan/basic/basic_stream.h
- include/seqan/sequence/segment_infix.h
- include/seqan/sequence/string_set_base.h
- include/seqan/stream/formatted_file.h
- manual/source/Tutorial/IndexedFastaIO.rst
- manual/source/Tutorial/StringSets.rst
> Yara hotfixes

- include/seqan/realign/realign_base.h
- include/seqan/sequence/segment_infix.h
I will merge this immediately if it doesn't break anything else.
> [fix] builds on windows for e7dccae

- include/seqan/realign/realign_base.h
- include/seqan/sequence/segment_infix.h
I will merge this immediately if it doesn't break anything else.
> [fix] builds on windows for e7dccae (develop)

- include/seqan/consensus/consensus_builder.h
- include/seqan/realign/realign_base.h
- include/seqan/store/store_all.h
> [fix] (hopefully all) remaining build issues on windows

- include/seqan/consensus/consensus_builder.h
- include/seqan/realign/realign_base.h
- include/seqan/store/store_all.h
> [fix] (hopefully all) remaining build issues on windows (develop)

- manual/source/Tutorial/Indices.rst
- manual/source/Tutorial/PatternMatching.rst
- manual/source/Tutorial/WritingTests.rst
- util/skel/test_template/test.h
This will close "trivial" parts of #920 . 
Errors in tutorials are fixed.
The contents of the slides are not maintained by Github system, so it will be handled separately.
> Trivial errors in tutorials are fixed.

- include/seqan/index/index_fm_rank_dictionary_wt.h
> Fix open() and save() for WT FMIndex

- include/seqan/stream/file_stream.h
- util/cmake/FindSeqAn.cmake
Fix one issue related to FreeBSD (triggered by both clang and g++) and one issue related to libc++ (which is also triggered on FreeBSD with Clang, but likely appears on other platforms, too).
@weese: can you briefly look at 809f698 ? Thank you!
This pull should resolve #936 .
> Fix/freebsd build issues (develop)

- include/seqan/sequence/adapt_std_list.h
As this is super minor, I will merge it, if nothing else breaks.
> Feature/add resize stdlist (develop)

- include/seqan/sequence/adapt_std_list.h
As this is super minor, I will merge it, if nothing else breaks.
> [FIX] adapt_list was missing resize

- include/seqan/sequence/string_array.h
- include/seqan/sequence/string_set_base.h
- include/seqan/sequence/string_set_concat_direct.h
- include/seqan/sequence/string_set_owner.h
- tests/sequence/CMakeLists.txt
- tests/sequence/test_sequence.h
- tests/sequence/test_string_set.h
- tests/sequence/test_stringset_v2.cpp
pull request for fix to #919 
Warning: apparently not all hotfixes from master have been pulled into develop yet. Merging this would merge another commit, as well.
> [FIXED-#919] fix and activate StringSet tests as well as other StringSet related fixes and additions (develop)

- include/seqan/score/score_simple.h
add documentation for a function (all other functions were already documented). Since it is only documentation I will merge later today, unless someone objects.
> [DOC] someone forgot doc for this function

- include/seqan/score/score_simple.h
> [DOC] someone forgot doc for this function (develop)

- include/seqan/bam_io/write_bam.h
- include/seqan/bam_io/write_sam.h
- include/seqan/score/score_simple.h
- include/seqan/sequence/segment_prefix.h
- include/seqan/sequence/segment_suffix.h
- manual/source/HowTo/UseSeqAnNodesInKnime.rst
> [FIXED-#828] Adds assertion to writeRecord of Bam/Sam IO. 

- apps/bs_tools/tests/run_tests.py
> [FIX] deactivate one test on freebsd [develop]

- include/seqan/platform.h
- include/seqan/sequence.h
- include/seqan/sequence/adapt_stl_container.h
- include/seqan/sequence/sequence_interface.h
Fix two issues in the new stl adaption that surprisingly broke the builds of razers3 on all platforms and everything on windows.
> [FIX] fix razers3 and hopefully also windows

- include/seqan/seeds/seeds_global_chaining.h
> [FIX] Chaining: Fixed bug in sparse chaining.

- include/seqan/seeds/banded_chain_alignment_impl.h
- include/seqan/seeds/banded_chain_alignment_traceback.h
- tests/seeds/test_align_banded_chain_impl.cpp
> [FIXED-#1020] BandedChainAlignment: Fixed bug in banded chain alignment

- apps/mason2/simulate_illumina.cpp
- apps/mason2/simulate_sanger.cpp
- include/seqan/basic/iterator_adapt_std.h
- include/seqan/basic/iterator_adaptor.h
- include/seqan/basic/iterator_counting.h
- include/seqan/basic/iterator_interface.h
- include/seqan/modifier/modifier_iterator.h
- include/seqan/modifier/modifier_reverse.h
- include/seqan/modifier/modifier_string.h
- include/seqan/modifier/modifier_view.h
- include/seqan/translation/translation.h
- tests/modifier/test_modifier.cpp
- tests/modifier/test_modifier_string.h
- tests/modifier/test_modifier_view.h
- tests/reduced_aminoacid/test_reduced_aminoacid.cpp
- tests/reduced_aminoacid/test_reduced_aminoacid.h
some modview related fixes and new tests.
Don't commit yet, some more cleanup needed.
> modified iterators and modview (again)

- apps/mason2/simulate_illumina.cpp
- apps/mason2/simulate_sanger.cpp
- include/seqan/basic/iterator_adapt_std.h
- include/seqan/basic/iterator_adaptor.h
- include/seqan/basic/iterator_counting.h
- include/seqan/basic/iterator_interface.h
- include/seqan/modifier/modifier_iterator.h
- include/seqan/modifier/modifier_reverse.h
- include/seqan/modifier/modifier_string.h
- include/seqan/modifier/modifier_view.h
- include/seqan/translation/translation.h
- tests/modifier/test_modifier.cpp
- tests/modifier/test_modifier_string.h
- tests/modifier/test_modifier_view.h
- tests/reduced_aminoacid/test_reduced_aminoacid.cpp
- tests/reduced_aminoacid/test_reduced_aminoacid.h
> modified iterators and modview (again) [develop]

- util/cmake/FindCXX14.cmake
Add code for c++14 compiler support detection.
> [FEATURE] detect c++14

- include/seqan/index/index_sa_qsort.h
> [FIX] remove warning that was due to incorrect parameter order [develop]

- include/seqan/bam_io/bam_file.h
- include/seqan/seq_io/fasta_fastq.h
- include/seqan/stream/formatted_file.h
- include/seqan/stream/stream_base.h
- include/seqan/stream/virtual_stream.h
> fix extensions (master)

- include/seqan/modifier/modifier_view.h
- include/seqan/sequence/string_set_concat_direct.h
- tests/reduced_aminoacid/test_reduced_aminoacid.cpp
- tests/reduced_aminoacid/test_reduced_aminoacid.h
> modstrings again... (develop)

- include/seqan/modifier/modifier_view.h
- include/seqan/sequence/string_set_concat_direct.h
- tests/reduced_aminoacid/test_reduced_aminoacid.cpp
- tests/reduced_aminoacid/test_reduced_aminoacid.h
> modstrings again... (master)

- include/seqan/bam_io/bam_file.h
> [FIX] remove warning (develop)

- include/seqan/index/index_sa_qsort.h
- include/seqan/index/index_shims.h
- include/seqan/index/index_wotd.h
- tests/index/test_index_stree_iterators.cpp
- tests/index/test_stree_iterators.h
Made trie and radix tree construction part of the public indexCreate() API.
> Trie construction

- include/seqan/bam_io/write_bam.h
> Fix Bam BIN computation

- util/makefile_project/src/main.cpp
> [FIX] Makefiles HowTo: fixed main.cpp

- include/seqan/align/dp_matrix.h
- include/seqan/align/matrix_base.h
- include/seqan/find/find_myers_ukkonen.h
- include/seqan/find/find_score.h
Fixes compiler errors and warnings under windows and gcc.
> [FIX] Fixes compiler errors introduced by #1070

- include/seqan/basic/basic_exception.h
- util/cmake/SeqAnBuildSystem.cmake
> Enables global exception handler only if macro is defined 

- include/seqan/stream/iostream_bgzf.h
- include/seqan/stream/iostream_bgzf_impl.h
- include/seqan/stream/iostream_bzip2.h
- include/seqan/stream/iostream_bzip2_impl.h
- include/seqan/stream/iostream_zip.h
- include/seqan/stream/iostream_zip_impl.h
- include/seqan/stream/iostream_zutil.h
- include/seqan/stream/stream_compressor.h
- include/seqan/stream/virtual_stream.h
> Fix directory structure for zipstream

- manual/source/Tutorial/SamBamIO.rst
This will close #1043. I added explanation section about BAM index according to https://github.com/holtgrewe/seqan-wiki/blob/master/Tutorial%252FSamBamIO.mediawiki.
> Manual: added a BAM index tutorial 

- include/seqan/store/store_io_gff.h
- manual/source/Tutorial/SamBamIO.rst
- tests/store/example.gff
- util/py_lib/seqan/dox/tpl/js/common.js
I added explanation section about BAM index according to https://github.com/holtgrewe/seqan-wiki/blob/master/Tutorial%252FSamBamIO.mediawiki
> Manual: added a BAM index tutorial

- util/py_lib/seqan/dox/tpl/js/common.js
- util/py_lib/seqan/dox/tpl/list.html
Hopefully this fixes it now for real.
> Fixes problem with close button in dox side pane.

- manual/source/StyleGuide/Cpp.rst
> Updated the Style Guide

- include/seqan/basic/fundamental_tags.h
- include/seqan/stream/buffered_stream.h
- include/seqan/stream/virtual_stream.h
- manual/source/Tutorial/SamBamIO.rst
- tests/bam_io/CMakeLists.txt
> Document class VirtualStream

- include/seqan/seq_io/fasta_fastq.h
> Use .raw extension for SeqIO's Raw format

- util/py_lib/seqan/dox/dox_parser.py
- util/py_lib/seqan/dox/dox_tokens.py
- util/py_lib/seqan/dox/proc_doc.py
- util/py_lib/seqan/dox/raw_doc.py
- util/py_lib/seqan/dox/test/test_dox_parser.py
- util/py_lib/seqan/dox/test/test_proc_doc.py
- util/py_lib/seqan/dox/test/test_raw_doc.py
- util/py_lib/seqan/dox/tpl/function.html
- util/py_lib/seqan/dox/tpl/macro.html
- util/py_lib/seqan/dox/tpl/sections.html
- util/py_lib/seqan/dox/write_html.py
Adds ```@datarace``` field to the dox to document possible data races for member interface and global functions.
It is set to: ```Thread safety unknown!``` for all functions that do not define this entity.
> Adds @datarace entity to dox.

- include/seqan/basic/basic_type.h
- include/seqan/basic/iterator_counting.h
- include/seqan/basic/iterator_position.h
- include/seqan/basic/iterator_range.h
- include/seqan/modifier.h
- include/seqan/modifier/modifier_position.h
- include/seqan/modifier/modifier_string.h
- include/seqan/parallel/parallel_algorithms.h
- include/seqan/sequence/segment_infix.h
- include/seqan/sequence/string_set_segment.h
- tests/basic/test_basic.cpp
- tests/basic/test_basic_type.h
- tests/modifier/test_modifier.cpp
- tests/modifier/test_modifier_string.h
* Implemented a lightweight Position ModifiedString
* Fixed CountingIterator
* Removed ConstParameter_<>
* Added getter stringSetPositions() to Segment StringSet
* Use Pointer_<> for inner host of Segment StringSet
* Wrapped more parallel STL algorithms
> Position ModifiedString and small related fixes

- include/seqan/blast/blast_tabular_out.h
forgot one commit in the last pull -.-
> [FIX] minor formatting issue

- include/seqan/blast/blast_tabular.h
> [INTERNAL] make fields iterable

- util/cmake/SeqAnBuildSystem.cmake
> Build System: find recursively all demos to be installed

- manual/source/conf.py
> Remove disqus from readthedocs

- include/seqan/blast/blast_record.h
- include/seqan/blast/blast_statistics.h
sorry for breaking it earlier this week....
> [DOC] fix dox in develop

- .travis.yml
> Travis: removed _build from cache

- demos/tutorial/fragment_store/access_aligned_reads.cpp
- demos/tutorial/fragment_store/access_aligned_reads2.cpp
Fixes fragment store demos on win builds.
> Hotfix: Fixes broken demo on win builds.

- include/seqan/stream/iostream_zip.h
- include/seqan/stream/iostream_zip_impl.h
See #1244. Merge conflicts due to replaying PR #1177 on master were solved locally.
> Rolled back, improved and cleaned-up the ZIP Stream

- include/seqan/index/index_fm.h
but instead use the documented metafunction.
> [FIX] don't force the use of Skew here

- apps/yara/mapper.h
- apps/yara/mapper_aligner.h
- apps/yara/mapper_writer.h
> Yara: follow SAM recommended practices for paired-end reads

- apps/razers2/outputFormat.h
- apps/stellar/stellar.cpp
- include/seqan/basic/iterator_adapt_std.h
- include/seqan/platform/platform_windows.h
- include/seqan/stream/buffered_stream.h
> Support Visual Studio 2015

- include/seqan/platform/platform_windows.h
> Disabled warning 4335 (VS10)

- apps/alf/CMakeLists.txt
- apps/bs_tools/CMakeLists.txt
- apps/dfi/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/fx_tools/CMakeLists.txt
- apps/gustaf/CMakeLists.txt
- apps/insegt/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/micro_razers/CMakeLists.txt
- apps/ngs_roi/CMakeLists.txt
- apps/pair_align/CMakeLists.txt
- apps/param_chooser/CMakeLists.txt
- apps/rabema/CMakeLists.txt
- apps/razers/CMakeLists.txt
- apps/razers2/CMakeLists.txt
- apps/razers3/CMakeLists.txt
- apps/rep_sep/CMakeLists.txt
- apps/sak/CMakeLists.txt
- apps/sam2matrix/CMakeLists.txt
- apps/samcat/CMakeLists.txt
- apps/searchjoin/CMakeLists.txt
- apps/seqan_flexbar/CMakeLists.txt
- apps/seqan_tcoffee/CMakeLists.txt
- apps/seqcons/CMakeLists.txt
- apps/seqcons2/CMakeLists.txt
- apps/sgip/CMakeLists.txt
- apps/snp_store/CMakeLists.txt
- apps/splazers/CMakeLists.txt
- apps/stellar/CMakeLists.txt
- apps/tree_recon/CMakeLists.txt
Except Yara which is tagged from develop.
The magic GNU sed command, courtesy of @temehi, is:
```
for a in apps/*/; do sed -i -r 's/set \(SEQAN_APP_VERSION \"([0-9]+\.)?([0-9]+\.)([0-9]+)\"\)/echo set \\(SEQAN_APP_VERSION \\"\1\2$((\3+1))\\"\\)/ge' $a/CMakeLists.txt; done;
```
> Bumped app versions for Release 2.0.1

- util/travis/linux-cibuild.cmake
> TravisCI: consider warnings as errors

- CHANGELOG.rst
> Changelog updated for 2.0.1

- include/seqan/basic/iterator_adapt_std.h
> [FIX] adapter iterator for const strings

- util/cmake/FindSeqAn.cmake
See https://github.com/seqan/seqan/pull/1215.
> Changed includes search priorities for CMake's FindSeqAn.

- util/cmake/SeqAnBuildSystem.cmake
> [FIX] replace spaces with underscores for icc

- include/seqan/index/index_shims.h
> fix read only index reading

- apps/gustaf/CMakeLists.txt
- apps/gustaf/README.rst
- apps/gustaf/stellar_routines.h
- util/cmake/FindSeqAn.cmake
I don't get why the other changes/commits are included here, they are already merged into develop. Is this my fault?
> Update Readme.rst Seqan project links

- include/seqan/sequence/string_set_concat_direct.h
- include/seqan/sequence/string_set_dependent_generous.h
- include/seqan/sequence/string_set_owner.h
- tests/sequence/CMakeLists.txt
- tests/sequence/test_string_set.h
> [Feature] StringSet: add insertValue, insert, replace 

- include/seqan/sequence/string_set_concat_direct.h
- include/seqan/sequence/string_set_dependent_generous.h
- include/seqan/sequence/string_set_owner.h
- tests/sequence/CMakeLists.txt
- tests/sequence/test_string_set.h
> [Feature] StringSet: add insertValue, insert, replace

- manual/source/Tutorial/PairwiseSequenceAlignment.rst
> Correction of CIGAR example

- dox/config.ini
Language entitiy "int x" will be changed to "var".
This will fix #1034.
> entity 'int x' to 'var' in API doc.

- util/cmake/SeqAnContribs.cmake
Generated contrib package for VS14 and added new package to SeqAnContribs.cmake
> [FEATURE] Build: Adds contrib support for vs14.

- .travis.yml
- util/travis/linux-cibuild.sh
> [FEATURE] new travis platforms + ccache

- util/cmake/SeqAnBuildSystem.cmake
> [FEATURE] Outputs the selected source dir when configuring sources.

- apps/yara/CMakeLists.txt
- apps/yara/README.rst
- apps/yara/bits_matches.h
- apps/yara/find_verifier.h
- apps/yara/mapper.cpp
- apps/yara/mapper.h
- apps/yara/mapper_verifier.h
- apps/yara/mapper_writer.h
- apps/yara/misc_options.h
- include/seqan/align/gaps_base.h
- include/seqan/parallel/parallel_algorithms.h
App changes
-----------------
* Added automatic paired-end library detection
* Added support for medium-size Indels
* Fixed some edge cases
* Added ICC native compilation flags
Library changes
---------------------
* Added functions ```countGapOpens()``` and ```countGapExtensions()``` to ```align/gaps_base.h```
* Changed ```iota()``` to take ```SEQAN_FORWARD_ARG```
> Yara v0.9.5

- include/seqan/bam_io/bam_tags_dict.h
> [FEATURE] Adds function to write tags from BamTagsDict to the tags field of a bam record.

- .travis.yml
This feature is needed for pull request #1352.
> Use cmake3.2 in travis builds.

- util/py_lib/seqan/dox/tpl/js/common.js
- util/py_lib/seqan/dox/write_html.py
This will fix #831 .
Check how it works : 
http://docs.seqan.de/seqan/master_version_test_832/?p=FragmentStore::PredefinedAnnotationTypes
> fix URIEncoding problem for entities with ::

- include/seqan/align/gaps_anchor.h
- include/seqan/align/gaps_array.h
- include/seqan/align/gaps_base.h
- include/seqan/align/gaps_iterator_anchor.h
- include/seqan/align/gaps_iterator_array.h
- include/seqan/align/gaps_iterator_base.h
- tests/align/test_align_gaps.h
- tests/align/test_align_gaps_iterator.h
Implements feature-requests: #527 and #528.
> [FEATURE] Left projection in gap structures

- demos/tutorial/blast/read_assignment.cpp
- demos/tutorial/blast/write_assignment.cpp
- include/seqan/blast.h
- tests/blast/test_blast.cpp
> [INTERNAL] deactivate blast module on windows again

- include/seqan/parallel/parallel_algorithms.h
followup to #1386 
@rrahn please review today, thanks!
> [FIX] PLATFORM_GNU instead of _GCC

- demos/blast/blast_in_lowlevel.cpp
- tests/blast/test_blast.cpp
> [FIX] another round of blast windows fixes

- apps/ngs_roi/project_interval.cpp
> Fixes VS 14 builds.

- util/py_lib/seqan/dox/tpl/js/common.js
- util/py_lib/seqan/dox/write_html.py
This will fix below 3 situations.
1. "::" in p
Before: http://docs.seqan.de/seqan/master/?p=ArgParseArgument::ArgumentType
(not working in window system)
After: http://docs.seqan.de/seqan/master_test_r/?p=ArgParseArgument::ArgumentType
2. multiple "#"s
Before : http://docs.seqan.de/seqan/master/?p=BamTagsDict#BamTagsDict%3A%3ABamTagsDict
After : http://docs.seqan.de/seqan/master_test_r/?p=BamTagsDict#BamTagsDict%3A%3ABamTagsDict
3. "_" in the middle of the file name
Before : http://docs.seqan.de/seqan/master/?p=SEQAN_HOST
After : http://docs.seqan.de/seqan/master_test_r/?p=SEQAN_HOST
> Dox issues about page redirection

- util/py_lib/seqan/dox/tpl/js/common.js
- util/py_lib/seqan/dox/write_html.py
This will fix below 3 situations.
1. "::" in p
Before: http://docs.seqan.de/seqan/master/?p=ArgParseArgument::ArgumentType
(not working in window system)
After: http://docs.seqan.de/seqan/master_test_r/?p=ArgParseArgument::ArgumentType
2. multiple "#"s
Before : http://docs.seqan.de/seqan/master/?p=BamTagsDict#BamTagsDict%3A%3ABamTagsDict
After : http://docs.seqan.de/seqan/master_test_r/?p=BamTagsDict#BamTagsDict%3A%3ABamTagsDict
3. "_" in the middle of the file name
Before : http://docs.seqan.de/seqan/master/?p=SEQAN_HOST
After : http://docs.seqan.de/seqan/master_test_r/?p=SEQAN_HOST
> Dox issues about page redirection.

- apps/yara/bits_matches.h
- apps/yara/mapper.cpp
- apps/yara/mapper.h
- apps/yara/mapper_verifier.h
- apps/yara/store_seqs.h
> Yara v0.9.5 fixes

- include/seqan/basic/iterator_adapt_std.h
- include/seqan/map/map_skiplist.h
* Fixes test_sequence_v2.
* Fixes error with geometric_distribution.
> Fixes build errors on windows platform

- apps/yara/bits_matches.h
@esiragusa your PR fixed the fails but introduced warnings:
http://cdash.seqan.de/viewBuildError.php?type=1&buildid=164104
so I have renewed my PR. Can you greenlight this?
> [FIX] build yara build warnings

- include/seqan/sequence/string_packed.h
> [WORKAROUND] fix insert() in packed_string 

- apps/yara/bits_matches.h
@h-2 fyi #1444 broke yara... please merge this one.
> Yara: fix static_cast regression

- apps/yara/bits_matches.h
- apps/yara/mapper.h
> Yara v0.9.6

- apps/bs_tools/CMakeLists.txt
- util/cmake/SeqAnBuildSystem.cmake
> fix freebsd nightly issues

- manual/source/Tutorial/DataStructures/Modifiers.rst
ModidiedString --> ModifiedString
> a typo in Modifiers section

- dox/CMakeLists.txt
- util/py_lib/seqan/dox/pure.py
- util/py_lib/seqan/dox/write_html.py
This will fix #1513.
It will change the default directory to /SOURCE/dox/ and write the result to /BUILD/dox/
> fix 'make package'

- include/seqan/basic/debug_test_system.h
- include/seqan/file/file_interface.h
- include/seqan/platform.h
- include/seqan/system.h
- include/seqan/system/file_forwards.h
- include/seqan/system/file_sync.h
> make async io optional 

- demos/tutorial/fragment_store/access_aligned_reads2.cpp
- manual/source/Tutorial/DataStructures/Store/FragmentStore.rst
I have fixed broken links and the solution of assignment 1.
> corrections for fragmentStore in manual

- manual/source/Tutorial/Algorithms/Realignment.rst
1) Add legend to the figure and the explanation becomes clearer.
2) The position 920 is incorrect, so I changed it.
* All the code examples work as stated.
> checking realignment tutorial

- demos/dox/index/open_save.cpp
- demos/tutorial/indices/base.cpp
- include/seqan/basic/debug_test_system.h
corresponds to master PR  #1535
>  [FIX] delete temporary files when running unit tests

- demos/dox/index/open_save.cpp
- demos/tutorial/indices/base.cpp
- include/seqan/basic/debug_test_system.h
> [FIX] delete temporary files when running unit tests

- include/seqan/basic/debug_test_system.h
Corresponds to master PR #1549.
> [FIX] Fixes windows warnings when deleting temporary files.

- util/cmake/SeqAnCtdSetup.cmake
- util/cmake/ctd/configure_profile_properties.cmake
- util/cmake/ctd/plugin.properties.in
> Knime packaging - configuration options for plugin.properties (develop)

- manual/source/Tutorial/HowTo/Recipes/AccessIndexFibres.rst
> [DOC] remove Pizza&Chili from manual

- util/cmake/SeqAnBuildSystem.cmake
> Fix #1572: disable building with -march=native for 32 bit target platforms

- util/cmake/SeqAnBuildSystem.cmake
> Fix #1572: disable building with -march=native for 32 bit target platforms (develop)

- demos/tutorial/indexed_fasta_io/base.cpp.stdout
- include/seqan/seq_io/fai_index.h
> [FIX] closes the fasta file after fai_index is built

- demos/tutorial/indexed_fasta_io/base.cpp.stdout
- include/seqan/seq_io/fai_index.h
> [FIX] closes the fasta file after fai_index is built (develop)

- demos/tutorial/graph/graph_hmm.cpp
- demos/tutorial/graph/solution_1.cpp
- manual/source/Tutorial/Algorithms/GraphAlgorithms.rst
- manual/source/Tutorial/DataStructures/Graphs.rst
Some minor changes to the style or content of the tutorial
> [DOC] Graphs Tutorial

- demos/tutorial/indices/base.cpp
- manual/source/Tutorial/Algorithms/PatternMatching/IndexedPatternMatching.rst
Minimal corrections for the pattern matching part.
This PR is related to #1403  and #955
> Manual pattern matching

- util/py_lib/seqan/dox/tpl/js/common.js
This will close #1531 .
(1) case 1 
Before : http://docs.seqan.de/seqan/master/?p=FragmentStore%3A%3AalignedReadStore 
After : http://docs.seqan.de/seqan/master_test_1531/?p=FragmentStore%3A%3AalignedReadStore 
(2) case 2 
Before : http://docs.seqan.de/seqan/master/?p=FragmentStore#compactAlignedReads
After : http://docs.seqan.de/seqan/master_test_1531/?p=FragmentStore#compactAlignedReads
> [FIX] broken links: manual -> dox 

- apps/bs_tools/casbar.cpp
@cpockrandt can you have a look ? :smiley:
> [FIX] deletes all temp files that are generated by the app bs_tools.

- demos/tutorial/index_iterators/index_search.cpp
- manual/source/Tutorial/DataStructures/Indices/IndexIterators.rst
Referring to #955
I'm not sure how outdated the referenced ticket is.
* I mentioned ``IndexSa`` (but I don't see any need to explain it separately in detail)
* tree vs. trie was already explained in the tutorial
I haven't replaced search trees with suffix trees yet because I didn't manage to draw pretty trees in time. Maybe I can finish this today and add it to the PR.
> Improve index iterators tutorials

- apps/yara/misc_types.h
> Yara: don't swallow base qualities

- include/seqan/basic/debug_test_system.h
> [FIX] temporarily disable warnings on windows when a temp directory c… (develop)

- include/seqan/arg_parse/arg_parse_argument.h
@h-2 as we have discussed I created this PR to maintain the API backward compatibility which was broken by #1524 and #1525. @esiragusa I can revert the commit to yara but that will cause a "deprecated" warning...
I do not see a reason to revert the previous  PRS and it will be doing the same thing twice.
> [API] fixes the broken API by #1524

- demos/tutorial/alignment/align_assignment1.cpp.stdout
- demos/tutorial/alignment/scoring_scheme_affine_dgs.cpp.stdout
> [FIX] fix test results

- demos/tutorial/blast_io/read_assignment.cpp
- demos/tutorial/blast_io/write_assignment.cpp
As requested, I changed the ``cerr`` for the release.
> [FIX] Temporarily changing stderr on Windows because of VS14 bug

- apps/yara/find_verifier.h
- apps/yara/mapper.h
- apps/yara/mapper_aligner.h
- apps/yara/mapper_writer.h
> Yara: fix CIGARs and secondary records

- README.rst
> [FIX] Fixed broken readthedocs links

- manual/source/Tutorial/GettingStarted/ParsingCommandLineArguments.rst
This does not correspond to any issue.
Just some typos and small changes to the content of the tutorial .
> [FIX, MANUAL] CLP - Some typos and small changes to the content.

- manual/source/Tutorial/DataStructures/Sequence/StringSets.rst
ConcatDirecet ->  ConcatDirect
> [DOC, FIX]  Typo in StringSet tutorial

- manual/source/Tutorial/DataStructures/Sequence/StringSets.rst
ConcatDirecet ->  ConcatDirect
> [DOC, FIX] Typo in StringSet tutorial (develop)

- demos/tutorial/indexed_fasta_io/solution2.cpp
- demos/tutorial/indexed_fasta_io/solution2.cpp.stderr
corresponds to master PR #1650
> [FIX] copy and paste typo.

- apps/fiona/fiona.cpp
- apps/searchjoin/join.cpp
- apps/searchjoin/search.cpp
- include/seqan/basic/basic_simd_vector.h
- include/seqan/blast/blast_base.h
- include/seqan/pipe/pool_base.h
- tests/journaled_string_tree/test_journaled_string_tree_traverser.h
- tests/platform/CMakeLists.txt
- tests/platform/test_platform.cpp
- tests/platform/test_platform_range_based_for_loops.h
- tests/reduced_aminoacid/test_reduced_aminoacid.h
- util/cmake/FindSeqAn.cmake
This fixes some bugs which allow building seqan with the intel compiler 16.0.2.
See ticket #1274
> [FEATURE] support intel compiler 

- apps/fiona/fiona.cpp
- apps/searchjoin/join.cpp
- apps/searchjoin/search.cpp
- include/seqan/basic/basic_simd_vector.h
- include/seqan/blast/blast_base.h
- include/seqan/pipe/pool_base.h
- tests/journaled_string_tree/test_journaled_string_tree_traverser.h
- tests/platform/CMakeLists.txt
- tests/platform/test_platform.cpp
- tests/platform/test_platform_range_based_for_loops.h
- tests/reduced_aminoacid/test_reduced_aminoacid.h
- util/cmake/FindSeqAn.cmake
This fixes some bugs which allow building seqan with the intel compiler 16.0.2.
See ticket #1274
> [FEATURE] support intel compiler (develop)

- include/seqan/basic/iterator_adapt_std.h
Fixes #1662 
Tested on klette (on develop only) and it worked :smiley: (see cdash)
> [FIX] Visual Studio 2015 Update 2 Bugfix

- manual/source/_static/seqan_ext.css
> [DOC, FIX] make content in console tag brighter

- demos/tutorial/pairwise_sequence_alignment/assignment5.cpp
- demos/tutorial/pairwise_sequence_alignment/assignment5.cpp.stdout
- demos/tutorial/pairwise_sequence_alignment/assignment5_step6.cpp
- demos/tutorial/pairwise_sequence_alignment/assignment5_step6.cpp.stdout
- manual/source/Tutorial/Algorithms/Alignment/PairwiseSequenceAlignment.rst
- manual/source/Tutorial/DataStructures/Indices/IndexIterators.rst
corrects assignment5 on pairwise alignment tutorial.
*  _assignment5.cpp_ and _assignment5_step6.cpp_ and their relative stdout files were changed.
* Relative document files were changed.
> [DOC,FIX] pairwisealigment assigment5 CIGAR correction(develop)

- manual/source/Infrastructure/Use/Install.rst
* use much nicer table
* add gentoo and openbsd
> [DOC] update install instructions in manual and use shiny table

- CONTRIBUTING.rst
A notive with a link to this file will be shown above new issues and pull requests.
> [DOC] add CONTRIBUTING.rst

- CHANGELOG.rst
- README.rst
- dox/pages/index.dox
- include/seqan/align/global_alignment_unbanded.h
- include/seqan/align/local_alignment_unbanded.h
- include/seqan/blast/blast_report_out.h
- include/seqan/blast/blast_tabular_in.h
- include/seqan/blast/blast_tabular_out.h
- include/seqan/seeds/banded_chain_alignment.h
- include/seqan/seq_io/fai_index.h
- manual/README
This will close #1715.
By this command :
grep -rl "readthedocs.org" * | xargs sed -i 's/readthedocs.org/readthedocs.io/g'
> [DOC,FIX] readthedocs.org -> readthedocs.io

- CHANGELOG.rst
- include/seqan/modifier.h
- include/seqan/modifier/modifier_padding.h
- tests/modifier/CMakeLists.txt
- tests/modifier/test_modifier.cpp
- tests/modifier/test_modifier_string_padding.h
Allows to expand a string with padding characters without touching the source.
> [FEATURE] Initial commit of padded modified string.

- demos/tutorial/indices/base.cpp
- include/seqan/basic/test_system.h
- include/seqan/file/file_mapping.h
- include/seqan/system/file_async.h
- include/seqan/system/file_sync.h
> [INTERNAL] Proper release file handles when destructing File<>

- apps/bs_tools/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/yara/CMakeLists.txt
See #1274 and especially this [comment](https://github.com/seqan/seqan/issues/1274#issuecomment-230749066).
> [INTERNAL] Enable bs_tools, fiona, mason2 and yara on windows (except for msvc)

- manual/source/Tutorial/DataStructures/Store/GenomeAnnotations.rst
Originally pointing to a SAM file.
> Corrected download link

- CHANGELOG.rst
- README.rst
- manual/source/Infrastructure/Use/CMakeBuildDirs.rst
Solves #1774 (document current compiler support)
> document current compiler support

- include/seqan/align/local_alignment_enumeration.h
- include/seqan/index/index_dfi.h
- include/seqan/index/index_esa_base.h
- include/seqan/index/index_fm.h
- include/seqan/index/index_pizzachili.h
- include/seqan/index/index_qgram.h
- include/seqan/index/index_qgram_openaddressing.h
- include/seqan/index/index_wotd.h
> [DOC] Added missing documentation for constructors

- manual/source/Infrastructure/Use/InstallDependencies.rst
> [FIX] Update ftp link for win contribs to latest package.

- include/seqan/align/dp_align_simd_helper.h
- include/seqan/modifier/modifier_padding.h
> [FIX] workaround problems with infixes and const-ness

- include/seqan/index/index_bidirectional.h
- include/seqan/index/index_bidirectional_stree.h
@cpockrandt please also add tests for this stuff :) thanks!
> [FIX] fix open/save overloads, add generic directional goDown, add representative()

- include/seqan/stream/formatted_file.h
- tests/bam_io/test_bam_file.h
- tests/bam_io/test_bam_io.cpp
- tests/bed_io/test_bed_io.cpp
- tests/gff_io/test_gff_io.cpp
- tests/gff_io/test_gff_io.h
- tests/roi_io/test_roi_io.cpp
- tests/seq_io/test_seq_io.cpp
- tests/seq_io/test_sequence_file.h
- tests/vcf_io/test_vcf_io.cpp
- tests/vcf_io/test_vcf_io.h
suggestion to #1834
@rrahn what do you think?
> [FEATURE] isOpen() function for formatted file.

- include/seqan/index/index_bidirectional_stree.h
@cpockrandt please review as soon as possible! Thx
> [FIX] overload resolution and const'ness of tags

- util/cmake/FindSeqAn.cmake
> [FIX] make seqan cmake module honor the QUIET parameter

- include/seqan/align/global_alignment_myers_hirschberg_impl.h
> [FIX] Remove debug output from algorithm.

- include/seqan/parallel/parallel_lock.h
Fixes hopefully some platform dependent issues described here: #1861
> [INTERNAL] Add platform specific cpu relax method for various platforms.

- include/seqan/parallel/parallel_lock.h
follow-up to #1887 in the long quest for solving #1861
> [FIX] forgot the semicolons on sparc

- include/seqan/gff_io/gff_io_base.h
> [FIX] skip extra space in gff/gtf records

- tests/basic/test_basic_simd_vector.h
> [FIX-#1867] Fixes build issues on mac os x.

- include/seqan/arg_parse/arg_parse_argument.h
- include/seqan/arg_parse/arg_parse_doc.h
also adapted display of options to show isList and numberOfValue information.
Fixes #838
> [FEATURE] Altered help page to display argument information

- include/seqan/store/store_io_gff.h
> [FIX] GFF records that have multiple parents

- include/seqan/blast/blast_record.h
- include/seqan/blast/blast_tabular_in.h
- include/seqan/blast/blast_tabular_out.h
- include/seqan/stream/tokenization.h
Add three more fields to the BlastMatch type and implement reading and writing functions for tabular output.
> [feature] add more BlastMatch fields, including accession and staxids

- manual/source/Tutorial/GettingStarted/BackgroundAndMotivation.rst
- manual/source/Tutorial/Workflows/GenerateKnimeNodes.rst
- manual/source/Tutorial/Workflows/KnimeReadySeqAnApp.rst
- manual/source/Tutorial/Workflows/UseSeqAnNodesInKnime.rst
> [Manual] fixes typos

- include/seqan/sequence/string_set_dependent_generous.h
> [FIX] Added length function for const dependent-generous-stringset.

- include/seqan/arg_parse/arg_parse_argument.h
- include/seqan/arg_parse/arg_parse_ctd_support.h
- include/seqan/arg_parse/arg_parse_doc.h
- include/seqan/arg_parse/arg_parse_option.h
- include/seqan/arg_parse/arg_parse_parse.h
- include/seqan/arg_parse/arg_parse_type_support.h
- include/seqan/arg_parse/argument_parser.h
- tests/arg_parse/test_app.ctd
- tests/arg_parse/test_arg_parse_argument.h
> [FEATURE] Added Argument types: bool, input_directory and output_directory

- CONTRIBUTING.rst
- manual/source/Infrastructure/Contribute/GitWorkflow.rst
> Update GitWorkflow tutorial and improve the contributor's rst

- include/seqan/blast/blast_tabular_out.h
Fixes warning and compiler error on wintel compiler.
> [FIX] Fixes wintel warnings.

- dox/CMakeLists.txt
- dox/dox_only.sh
- dox/run.sh
It will find python2.x and change python path in .sh accordingly.
This will close #1482.
It is also related to #1916.
> [FIX] Change python path in .sh files 

- apps/alf/CMakeLists.txt
- apps/bs_tools/CMakeLists.txt
- apps/dfi/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/fx_tools/CMakeLists.txt
- apps/gustaf/CMakeLists.txt
- apps/insegt/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/micro_razers/CMakeLists.txt
- apps/ngs_roi/CMakeLists.txt
- apps/pair_align/CMakeLists.txt
- apps/param_chooser/CMakeLists.txt
- apps/rabema/CMakeLists.txt
- apps/razers/CMakeLists.txt
- apps/razers3/CMakeLists.txt
- apps/rep_sep/CMakeLists.txt
- apps/sak/CMakeLists.txt
- apps/sam2matrix/CMakeLists.txt
- apps/samcat/CMakeLists.txt
- apps/searchjoin/CMakeLists.txt
- apps/seqan_tcoffee/CMakeLists.txt
- apps/seqcons2/CMakeLists.txt
- apps/sgip/CMakeLists.txt
- apps/snp_store/CMakeLists.txt
- apps/splazers/CMakeLists.txt
- apps/stellar/CMakeLists.txt
- apps/tree_recon/CMakeLists.txt
- apps/yara/CMakeLists.txt
.. using the one-liner in https://github.com/seqan/seqan/wiki/Release-Checklist
> Bump up app versions for seqan 2.3.0

- include/seqan/arg_parse/arg_parse_type_support.h
- tests/arg_parse/test_arg_parse.cpp
- tests/arg_parse/test_arg_parse.h
Please merge as soon as possible..
> [HOTFIX, TEST] Corrected boolean argument list of false-values

- include/seqan/arg_parse/arg_parse_version_check.h
> [HOTFIX] Excluded MESSAGE_REGISTERED_APP_UPDATE from release mode.

- include/seqan/arg_parse/arg_parse_version_check.h
- tests/arg_parse/test_arg_parse_version_check.h
> [HOTFIX] Different timestamp files for debug and release mode.

- README.rst
- manual/source/Infrastructure/Use/CustomBuildSystem.rst
- manual/source/Infrastructure/Use/FindSeqAnCMake.rst
> gcc 4.9 static build issues

- include/seqan/seq_io/sequence_file.h
- tests/seq_io/test_tag_select_intersect.h
> [FIX] guard Bam tag with SEQAN_HAS_ZLIB

- apps/bs_tools/CMakeLists.txt
- tests/platform/test_platform_range_based_for_loops.h
- util/cmake/SeqAnConsistentFPFlags.cmake
Fix intel compiler17 warnings/errors (i.e. ranged based for loops warning and bs_tools rounding issue)
> Fix intel compiler17 warnings

- manual/source/Infrastructure/Use/FindSeqAnCMake.rst
fixes #1997 
Reverts 44159bef2c793dbf75b65a8ff8a8ed3e3abc7713
> [FIXES-#1997] Reverts documentation about including the FindSeqAn.cmake.

- include/seqan/arg_parse/arg_parse_ctd_support.h
- tests/arg_parse/test_app.ctd
- tests/arg_parse/test_arg_parse_ctd_support.h
> [FIXES-#2026] Fixes gnk ctd problems.

- util/pkgconfig/seqan.pc.in
supersedes #2000 which is created against develop
> [FIX] remove flag that was not being set by cmake anymore, anyhow

- demos/tutorial/parsing_command_line_arguments/base.cpp
- manual/source/Tutorial/GettingStarted/ParsingCommandLineArguments.rst
> [MANUAL] Detailed Description and Disclaimer of Version Update Feature

- apps/seqan_tcoffee/README
- apps/seqan_tcoffee/seqan_tcoffee.cpp
- include/seqan/basic/alphabet_residue.h
- include/seqan/graph_algorithms/maximum_weighted_matching.h
This PR implements Iupac alphabet input for seqan_tcoffee, provides conversion from Iupac to Rna5 alphabet, and adds the greedy maximum weighted matching algorithm for arbitrary graphs with optional look-ahead.
> [FEATURE] Iupac to Rna5 conversion and MWM implementation

- include/seqan/align/dp_algorithm_impl.h
- include/seqan/align/dp_align_simd_helper.h
- include/seqan/align/dp_meta_info.h
- include/seqan/align/dp_scout_simd.h
- include/seqan/align/dp_traceback_impl.h
Refactors the variable length simd implementation to gain some more speed.
> [INTERNAL] Improve variable length SIMD alignment.

- include/seqan/bam_io/bam_index_bai.h
- tests/bam_io/test_bam_index.h
> [FIX] fixed hasAlignements logic

- apps/seqan_tcoffee/seqan_tcoffee.cpp
- include/seqan/graph_msa/graph_align_tcoffee_library.h
> proper t-coffee error message if global alignment fails

- include/seqan/arg_parse/arg_parse_version_check.h
> [FIX] language in arg_parser

- include/seqan/index/index_bifm_stree.h
- include/seqan/index/index_fm_stree.h
- include/seqan/index/index_sa_stree.h
- tests/index/test_index_stree_iterators.cpp
- tests/index/test_stree_iterators.h
> [FIX] goDown on empty string should not have any effects on the iterator

- include/seqan/align/gaps_base.h
> [DOX]  Fixed documentation of function isCharacter()

- manual/source/Tutorial/DataStructures/Indices/StringIndices.rst
> [DOC] Index construction: hint regarding disk/space quota

- include/seqan/basic/allocator_interface.h
> compiler warnings on gcc7

- manual/source/Infrastructure/Use/CustomBuildSystem.rst
- manual/source/Infrastructure/Use/FindSeqAnCMake.rst
> [DOC] document intel compiler specifics

- include/seqan/basic/fundamental_concepts.h
- tests/basic/test_basic_concept.cpp
- tests/basic/test_basic_concepts.h
> [FEATURE] Adds MoveConstructible concept.

- apps/mason2/fragment_generation.h
- include/seqan/basic/holder_tristate.h
- util/cmake/SeqAnSimdUtility.cmake
> Fix Clang6.0 warnings

- apps/mason2/mason_materializer.cpp
- apps/mason2/mason_splicing.cpp
- include/seqan/basic/alphabet_simple_type.h
- include/seqan/basic/pair_bit_compressed.h
- include/seqan/basic/pair_packed.h
- include/seqan/journaled_string_tree/journaled_string_tree_traverser_util.h
- include/seqan/seeds/banded_chain_alignment_impl.h
- include/seqan/simd/simd_base_seqan_impl_avx2.h
- include/seqan/simd/simd_base_seqan_impl_sse4.2.h
- include/seqan/system/file_async.h
- tests/align/CMakeLists.txt
- tests/basic/test_basic_exception.h
- tests/stream/test_stream_lexical_cast.h
> Fix Gcc8 warnings

- include/seqan/simd/simd_base.h
- include/seqan/simd/simd_base_seqan_impl_avx2.h
- include/seqan/simd/simd_base_seqan_impl_sse4.2.h
- include/seqan/simd/simd_base_seqan_interface.h
- include/seqan/simd/simd_base_umesimd_impl.h
- tests/simd/test_simd_vector.h
Add seqan::min function for simd vectors.
> Add seqan::min function for simd vectors

- tests/rna_io/CMakeLists.txt
- tests/simd/CMakeLists.txt
- util/cmake/SeqAnSimdUtility.cmake
- util/cmake/seqan-config.cmake
supersedes #2006 
(this time against develop)
>  [FIX] always include pthread with whole-archive

- util/cmake/SeqAnContribs.cmake
Needed to get a cleaner test environment for the CI builds via Jenkins
> [INTERNAL] Allow the contrib package to be found by looking up an environment variable.

- util/py_lib/seqan/dox/tpl/sections.html
> [FIXED-#2123] Updated default data race text for API documentation.

- include/seqan/stream/iter_stream.h
> [FIXED-#2104] Fixes sanitiser issue with StreamBuffer implementation.

- include/seqan/align/local_alignment_waterman_eggert_impl.h
- tests/align/test_alignment_algorithms_local.h
- tests/align/test_alignment_algorithms_local_banded.h
> [FIXED-#1508] Fixes local alignment enumerator for scoring matrices.

- apps/razers/tests/run_tests.py
- apps/searchjoin/tests/run_tests.py
- apps/yara/tests/run_tests.py
- include/seqan/bam_io.h
- include/seqan/bam_io/bam_alignment_record.h
- include/seqan/bam_io/bam_index_bai.h
- include/seqan/bam_io/bam_sam_conversion.h
- include/seqan/bam_io/bam_tags_dict.h
- include/seqan/bam_io/read_bam.h
- include/seqan/basic/basic_stream.h
- include/seqan/parallel/parallel_lock.h
- include/seqan/platform.h
- include/seqan/seq_io/bam_sam.h
- include/seqan/stream/file_stream.h
- include/seqan/stream/stream_compressor.h
- include/seqan/stream/tokenization.h
- tests/bam_io/test_bam_sam_conversion.h
- tests/index/test_index_fm_rank_dictionary.cpp
- tests/translation/test_translation.h
> fix issues on non-intel/amd platforms

- include/seqan/modifier/modifier_padding.h
- tests/modifier/test_modifier.cpp
- tests/modifier/test_modifier_string_padding.h
> [FIXED-#2190] Fixes const-propagation issue in Padding-Modifier Type.

- include/seqan/seeds/seeds_global_chaining.h
- tests/seeds/test_seeds_global_chaining.cpp
> [FIXED-#2082] Fixes sparse chaining algorithm.

- apps/alf/alf.cpp
- apps/fiona/compute_gain.cpp
- apps/mason2/mason_genome.cpp
- apps/mason2/mason_variator.cpp
- apps/rabema/rabema_build_gold_standard.cpp
- apps/rabema/rabema_evaluate.cpp
- apps/stellar/stellar.cpp
> [APPS] Changed all soft coded sequence file extensions to SeqFileOut/In::getFileExtensions().

- apps/seqan_tcoffee/tests/run_tests.py
Hopefully the final fix for #2141
> [INTERNAL] skip seqan_tcoffee tests on some platforms

- README.rst
- include/seqan/platform.h
- util/cmake/seqan-config.cmake
> drop icpc 16 support in seqan2.4

- include/seqan/basic/pair_packed.h
> [FIX#2186] yara-mapper seg-faults with the intel compiler

- include/seqan/sequence/string_base.h
> fix issue with google test

- include/seqan/align/dp_algorithm_impl.h
- include/seqan/align/dp_cell_dynamic.h
- include/seqan/align/dp_matrix_navigator_trace_matrix.h
- include/seqan/align/dp_traceback_impl.h
- include/seqan/align/gaps_anchor.h
- include/seqan/align_split/align_split_interface.h
- include/seqan/basic/fundamental_tags.h
- include/seqan/find/find_myers_ukkonen.h
- include/seqan/find/find_score.h
- include/seqan/index/find2_backtracking.h
- include/seqan/index/find_index_lambda.h
- include/seqan/index/find_index_qgram.h
- include/seqan/index/index_esa_stree.h
- include/seqan/journaled_string_tree/delta_map.h
- include/seqan/journaled_string_tree/journaled_string_tree_impl.h
- include/seqan/journaled_string_tree/journaled_string_tree_traverser_util.h
- include/seqan/platform.h
- include/seqan/seeds/banded_chain_alignment_impl.h
- include/seqan/seeds/banded_chain_alignment_traceback.h
- include/seqan/store/store_all.h
- include/seqan/store/store_io_sam.h
- include/seqan/stream/file_stream.h
- include/seqan/stream/iter_stream.h
- include/seqan/stream/virtual_stream.h
> add SEQAN_IF_CONSTEXPR

- apps/pair_align/CMakeLists.txt
- apps/razers/CMakeLists.txt
- apps/searchjoin/CMakeLists.txt
to bring down build and test time
> [INTERNAL] deactivate some apps on travis

- include/seqan/parallel/parallel_algorithms.h
> [FIX] Make count variable signed to satisfy OMP 2.0 specs

- include/seqan/simd/simd_base_seqan_impl.h
> [FIX#2223] "No supported platform for SIMD vectorization!" on PPC64

- util/cmake/SeqAnBuildSystem.cmake
> [FIX] Set CMP0054 policy also within SeqAnBuildSystem.cmake for internal build.

- include/seqan/translation/translation.h
- tests/translation/test_translation.h
add sanity checks and tests that provoke them.
fixes #2228 / seqan/lambda#111
> [FIXES-#2228,TEST] handle empty input correctly in translate()

- manual/source/Tutorial/GettingStarted/AFirstExample.rst
- manual/source/Tutorial/GettingStarted/BackgroundAndMotivation.rst
This will fix #2032 
Broken links in "background and motivation" tutorial have been fixed.
> [DOX] fix broken links in background_and_motivation tutorial

- include/seqan/bed_io/bed_record.h
> [DOX] Fixes correct names for class members.

- CHANGELOG.rst
- README.rst
none of this is tested so I will merge as soon as someone says go
> 2.4.0/changelog

- include/seqan/stream/iostream_bgzf.h
- include/seqan/stream/stream_compressor.h
Fixes #1927 
Do not merge yet.
I need to look into something first.
But you can have a first review on the changes.
> [FIX] Fixes correct detection of end-of-file marker and some synchronisation issue.

- include/seqan/bam_io/read_bam.h
> [FIXES-#2245] prevent wrong over/underflow on platforms where char is unsigned

- tests/index/test_index_bifm.cpp
- tests/translation/test_translation.h
> [FIX,TEST] deactivate some more tests on alpha

- apps/alf/CMakeLists.txt
- apps/bs_tools/CMakeLists.txt
- apps/dfi/CMakeLists.txt
- apps/fiona/CMakeLists.txt
- apps/fx_tools/CMakeLists.txt
- apps/gustaf/CMakeLists.txt
- apps/insegt/CMakeLists.txt
- apps/mason2/CMakeLists.txt
- apps/micro_razers/CMakeLists.txt
- apps/ngs_roi/CMakeLists.txt
- apps/pair_align/CMakeLists.txt
- apps/param_chooser/CMakeLists.txt
- apps/rabema/CMakeLists.txt
- apps/razers/CMakeLists.txt
- apps/razers3/CMakeLists.txt
- apps/rep_sep/CMakeLists.txt
- apps/sak/CMakeLists.txt
- apps/sam2matrix/CMakeLists.txt
- apps/samcat/CMakeLists.txt
- apps/searchjoin/CMakeLists.txt
- apps/seqan_tcoffee/CMakeLists.txt
- apps/seqcons2/CMakeLists.txt
- apps/sgip/CMakeLists.txt
- apps/snp_store/CMakeLists.txt
- apps/splazers/CMakeLists.txt
- apps/stellar/CMakeLists.txt
- apps/tree_recon/CMakeLists.txt
- apps/yara/CMakeLists.txt
(WHY WASNT THIS DONE AFTER LAST RELEASE?)
> bump app version numbers for release 2.4.0

- apps/mason2/CMakeLists.txt
- util/cmake/seqan-config.cmake
> [FIXES-#2268] further pthread fixes on old ubuntu

- include/seqan/graph_types/graph_drawing.h
- manual/source/Tutorial/DataStructures/Graphs.rst
> [DOX] Fix documentation of writeRecords function for Graphs.

- CHANGELOG.rst
Added recent yara changes:
- Fixed verification of N's for seeds and boundary checking for anchors (restores full-sensitivity)
- Removed option --all (was deprecated)
- Added option to compute and output alignments for secondary matches
- Added option to specify strata threshold as absolute number of errors
> Update Changelog (yara)

- demos/tutorial/simple_genome_alignment/lagan.cpp
- manual/source/Tutorial/HowTo/UseCases/SimpleGenomeAlignment.rst
> [FIX] Some typos and adding include modules. 

- include/seqan/basic/iterator_adaptor.h
> [FIX] GCC8 Warning

- include/seqan/arg_parse/arg_parse_ctd_support.h
- tests/arg_parse/test_app.ctd
> [INTERNAL] Fix ctd output: add ctdVersion tag in header.

- include/seqan/basic/alphabet_math.h
Hi,
this is a follow-up to PR #2348.
See how it works this time ...
Best regards,
Christian
> [FIX-#2347] Mini-Fix for using C++-conformant numerical limits

- .travis.yml
- include/seqan/graph_align/graph_impl_align_adapt.h
- include/seqan/graph_types/graph_iterator_outedge.h
Adds libxml2-utils to ubunut installation to enable ctd_tests.
fixes #2365
> [FIX] Fixes the ctd tests on travis.

- include/seqan/parallel/parallel_lock.h
Fixes https://github.com/seqan/seqan/issues/2281
> [Fix] Thread wait for IA64

- dox/CMakeLists.txt
> [FIX] Check for jinja2 when building dox

- include/seqan/basic/iterator_base.h
This was fixed by removing const from return type of operator++.
> [FIX] The precrement operator of SeqAn iterators doesn't statisfy the (Weakly)Incrementable concept

- include/seqan/modifier/modifier_shortcuts.h
Does someone want to look at this or can I merge it after CI passes?
> [FIX] constrain complement() functions

- README.rst
merge master to develop so develop get's the SeqAn3 note as well
> Add note about SeqAn3

- apps/micro_razers/micro_razers.cpp
The reason is because readFileNames[0] is not defined yet.
> If output is not defined segmentation fault is happens

- .github/workflows/deploy_dox.yml
This PR will deploy the documentation ~~every hour and deploy the generated html pages on our dedicated server. The correct dir to sync to must be set after the PR get's merged in order to test that the correct path is set.~~
Ok the last point is already resolved by only triggering the pipeline on push events on the develop or master branch
> [INFRA] Add github workflow to deploy dox

- include/seqan/graph_types/graph_iterator_dfs.h
Name fixed to be consistent with tag name present in code
> [DOC] Changed DfsPreorderIterator to DfsPreorder

- include/seqan/modifier/modifier_padding.h
Can a get a re---view? :notes:
> [FIX] da padding-view

- .github/workflows/cancel.yml
- .github/workflows/ci.yml
For Linux and MacOS, couldn't get it to use MSVC 14.0 though it should be possible.
For windows it's also probably better to switch to CMake scripting since the languages differ too much (https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml).
> [INFRA] Use GitHub actions

- .github/workflows/documentation.yml
> [FIX] Path of environment.yml

- README.rst
I'll use this PR to send triggers to Jenkins (PR reopened triggers).
PR synchronize events don't seem to work...
When I'm done, I'll convert this PR to do something useful: Updating the linked badge in the README (the old URL is invalid).
> [FIX] Documentation Badge

- include/seqan/align/dp_cell_dynamic.h
- include/seqan/align_parallel/parallel_align_interface.h
- include/seqan/basic/fundamental_tags.h
- include/seqan/simd/simd_base_seqan_impl.h
Blocked by https://github.com/seqan/seqan/pull/2448
The last commits contains some fixes (workarounds) that make icpc work for me.
Also see https://github.com/seqan/product_backlog/issues/261#issuecomment-748262888
> [INFRA] Intel compiler support

- apps/mason2/mason_genome.cpp
- apps/mason2/mason_options.h
- apps/mason2/simulate_genome.cpp
- manual/environment.yml
This allows to simulate genomes > 2 GiB
> [MISC] Use 64 bit integers for contig lengths

- .github/workflows/ci.yml
- include/seqan/basic/triple_base.h
- tests/align_parallel/test_align_wavefront_alignment_scheduler.h
The first two commits are fixes for icc that appear with `-std=c++20`. The previous PR fixed all the things that happened with `-std=c++17`
> [INFRA] Add icc on Linux to CI

- util/py_lib/seqan/app_tests.py
We tried to call `read()` on `subprocess.PIPE` (which is an integer).
That means, if there was an error, we threw a python error instead of printing the stdout/stderr.
> [FIX] app_test script

- include/seqan/stream/formatted_file.h
Fix copy constructor to make this copyable.
> [FIX] real copy constructor

- .github/workflows/ci.yml
See https://github.com/seqan/seqan3/pull/2507
> [FIX,INFRA] Use up-to-date homebrew on macOS

- .github/workflows/ci_icc.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_macos.yml
- .github/workflows/ci_win.yml
- .github/workflows/documentation.yml
- CHANGELOG.rst
- CONTRIBUTING.rst
- README.md
- dox/pages/index.dox
- manual/attic/HowTo/UseGit.rst
- manual/source/Infrastructure/Contribute/GitWorkflow.rst
- manual/source/Infrastructure/Manage/RepositoryStructure.rst
- manual/source/Infrastructure/Use/Install.rst
- manual/source/conf.py
- util/py_lib/seqan/auto_build.py
This the preparation to rename the `master` branch to `main`
> fix: rename master to main

- apps/mason2/mason_options.cpp
> [DOC] Add caveats section for mason

- include/seqan/basic/array_construct_destruct.h
> [MISC] Expand gcc workaround

- apps/mason2/genomic_variants.cpp
- apps/mason2/genomic_variants.h
> [FIX] mason

- .github/workflows/ci_sanitizer.yml
- apps/fiona/fiona.cpp
- apps/stellar/stellar_extension.h
- demos/dox/align_split/split_alignment.cpp
- include/seqan/align_parallel/parallel_align_interface.h
- include/seqan/align_parallel/wavefront_alignment_scheduler.h
- include/seqan/align_parallel/wavefront_task_scheduler.h
- include/seqan/bam_io/bam_sam_conversion.h
- include/seqan/bam_io/read_bam.h
- include/seqan/basic/allocator_singlepool.h
- include/seqan/basic/array_construct_destruct.h
- include/seqan/index/index_skew7.h
- include/seqan/index/pipe_merger7.h
- include/seqan/parallel/enumerable_thread_local.h
- include/seqan/pipe/pipe_source.h
- include/seqan/sequence/sequence_interface.h
- include/seqan/stream/iostream_bgzf.h
- include/seqan/stream/stream_compressor.h
- tests/align_parallel/test_align_wavefront_alignment_scheduler.h
- tests/basic/test_basic_aggregate.h
- tests/parallel/test_parallel_thread_pool.h
- util/cmake/SeqAnSimdUtility.cmake
This adds a Sanitizer cron job and fixes various errors.
Disabled options:
* `detect_leaks=0`
* `-fno-sanitize=alignment`
CTest exclusions are because of a too long runtime for GH actions (max is 6 hours).
> [FIX,INFRA] Sanitizer builds

- apps/fiona/CMakeLists.txt
- apps/ngs_roi/bam2roi.cpp
- include/seqan/basic/basic_stream.h
- util/bin/demo_checker.py
- util/cmake/SeqAnBuildSystem.cmake
- util/py_lib/seqan/app_tests.py
https://salsa.debian.org/med-team/seqan2/-/tree/a55e2629beae9d645ebe37b7b9d501e3ab473c19/debian/patches
|            **Patch**            |        **Note**       |     **Status**     |
|:-------------------------------:|:---------------------:|:------------------:|
| ctdVersion.patch                | backport of upstream  | :heavy_check_mark: |
| fix_manpage_formatting.patch    | backport of upstream  | :heavy_check_mark: |
| fix_python3_tests               | included in PR        | :heavy_check_mark: |
| fix-version_check-test          | could not reproduce   | :question:         |
| ia64_yield                      | backport of upstream  | :heavy_check_mark: |
| install_fiona_illumina          | included in PR        | :heavy_check_mark: |
| no-unaligned-access.patch       | included in …
> [INFRA] Apply Debian patches

- include/seqan/index/find_swift.h
Overloaded `createHit` in application code instead https://github.com/eaasna/valik/pull/151
> [MISC] Assert that SWIFT hit is within underlying query sequence bounds

- manual/source/Infrastructure/Manage/Releases.rst
- manual/source/Infrastructure/Use/Install.rst
- manual/source/Infrastructure/Use/InstallDependencies.rst
> [DOC] Update packages
